export const FUN_FACTS = [
  "Creepers exist because a developer accidentally stretched a pig model vertically instead of horizontally.",
  "Endermen were inspired by the Slender Man myth and a glitched, stretched zombie texture.",
  "A full Minecraft day-night cycle lasts 20 real-world minutes and contains 24,000 game ticks.",
  "Ghasts make some of their sounds from recordings of a sleeping cat.",
  "The Far Lands, a terrain corruption bug from extreme world coordinates, was patched out in Beta 1.8.",
  "Diamond tools were once a placeholder texture for stronger tools before the gem got its design.",
  "Villagers can float and swim through water, but they cannot breathe underwater.",
  "The 'cave sounds' you hear are intentional ambient triggers, not random mob noises.",
  "A nether portal only needs a minimum frame of 4x5 blocks, with the interior hollowed out.",
  "Foxes can pick up items in their mouths, and a held enchanted weapon can affect their attacks.",
  "Adult piglins are neutral toward players wearing at least one piece of gold armor, unless the player provokes them.",
  "The Wither was the first boss mob the player could summon manually, by building its structure.",
  "Axolotls are bred by feeding two adults a bucket of tropical fish.",
  "Striders are immune to lava and will avoid water unless you're holding a warped fungus on a stick.",
  "Bedrock Edition and Java Edition use entirely different world generation algorithms, despite looking similar.",
  "The totem of undying was added specifically to make the Evoker boss fight more forgiving.",
  "Lightning striking a pig will turn it into a zombified piglin in Bedrock Edition.",
  "Sniffers were voted in by the community and are the first mob revived from extinction in-game.",
  "A fully enchanted netherite sword still can't out-damage a critical hit with a regular diamond sword.",
  "The Warden detects players through vibrations and sculk sensors, not sight — it has no eyes.",
  "Water placed beside farmland can hydrate it up to four blocks away on the same level.",
  "A redstone signal has strength levels from 0 to 15 and normally loses one level for each block of redstone dust it travels.",
  "Comparators can read how full many containers are and turn that fullness into a redstone signal.",
  "Silk Touch lets you collect blocks such as glass, ice, and ore blocks in forms that normally break or drop something else.",
  "Fortune increases drops from many ores and crops, but it does not combine with Silk Touch on the same tool.",
  "A conduit grants Conduit Power underwater when built inside a valid prismarine frame.",
  "Respiration extends underwater breathing time, while Aqua Affinity removes the normal underwater mining-speed penalty.",
  "Nether coordinates correspond to Overworld coordinates at an eight-to-one horizontal ratio.",
  "Beds set a player's spawn point in the Overworld, but attempting to sleep in one in the Nether or End causes it to explode.",
  "Honey blocks slow entities sliding down their sides and can move entities with sticky-piston machines.",
  "Packed ice and blue ice do not melt from nearby light sources, unlike regular ice.",
  "Mobs generally cannot spawn on bottom slabs, but they can spawn on top slabs because those form a full upper surface.",
  "A campfire can cook up to four food items at once without consuming additional fuel.",
  "Naming a mob with a name tag usually prevents it from naturally despawning.",
];

export const JOKES = [
  "Why did the skeleton stay home? It had no body to go with.",
  "Why don't creepers ever apologize? They always blow things out of proportion.",
  "Why did the villager refuse to trade? He didn't like the haggle.",
  "Why did the Enderman bring a ladder? To reach new heights without teleporting.",
  "Why was the redstone engineer always calm? Nothing they built could ever rage quit.",
  "Why did the zombie cross the road? The villager's door was unlocked.",
  "What did the diamond say to the pickaxe? You're the one mining my business.",
];
