// ─────────────────────────────────────────────────────────────────────────────
// verity_responses_7.js
// "Mini Minecraft Wiki" – 400+ entries + generic fallback.
// All responses are phase‑aware (p = 0–5).
// Uses utilities from verity_core.
// ─────────────────────────────────────────────────────────────────────────────

import { currentDay, ph, pick } from "./verity_core.js";

// ─────────────────────────────────────────────────────────────────────────────
// WIKI DATABASE – keyed by lowercase, singular names.
// Each value is a short, factual description.
// ─────────────────────────────────────────────────────────────────────────────

const WIKI = {
  // ─── BLOCKS ──────────────────────────────────────────────────────────────
  // Ores
  "coal ore": "A block that drops coal when mined. Found in most biomes at any depth.",
  "iron ore": "A common ore that drops raw iron. Found in caves and mountains.",
  "gold ore": "A rare ore found deep underground, especially in badlands.",
  "diamond ore": "A rare ore found deep underground (Y -58 to -64). Drops diamonds.",
  "emerald ore": "An ore found only in mountain biomes. Drops emeralds.",
  "redstone ore": "An ore that drops redstone dust. Found deep underground.",
  "lapis lazuli ore": "An ore that drops lapis lazuli, used for enchanting. Found deep underground.",
  "copper ore": "A common ore found underground. Drops raw copper.",
  "nether quartz ore": "An ore found in the Nether that drops nether quartz.",
  "nether gold ore": "An ore in the Nether that drops gold nuggets.",
  "ancient debris": "A rare block in the Nether that can be smelted into netherite scrap.",
  "deepslate": "A stone variant found deep underground. Replaces stone at Y=0 and below.",
  "deepslate diamond ore": "Diamond ore embedded in deepslate. Same drop rate.",
  "deepslate emerald ore": "Emerald ore in deepslate. Rare.",
  "deepslate gold ore": "Gold ore in deepslate. Found at deeper levels.",
  "deepslate iron ore": "Iron ore in deepslate. Common at deep levels.",
  "deepslate redstone ore": "Redstone ore in deepslate. Found deep.",
  "deepslate lapis lazuli ore": "Lapis lazuli ore in deepslate.",
  "deepslate copper ore": "Copper ore in deepslate.",
  "raw iron block": "A block of raw iron. Decorative, can be smelted.",
  "raw gold block": "A block of raw gold. Decorative.",
  "raw copper block": "A block of raw copper. Decorative.",
  "netherite block": "A block of netherite. Used for crafting and decoration.",
  "amethyst block": "A decorative block made from amethyst shards.",
  "budding amethyst": "A block that grows amethyst clusters over time.",
  "tuff": "A stone variant found in deep underground and in tuff blocks.",
  "calcite": "A white stone found in amethyst geodes.",
  "dripstone block": "A block that forms stalactites and stalagmites.",
  "pointed dripstone": "A pointed block that can drip water or lava.",
  "sculk": "A dark block found in the deep dark. Spreads when mobs die nearby.",
  "sculk shrieker": "A block that alerts the Warden when triggered.",
  "sculk catalyst": "A block that spreads sculk when mobs die nearby.",
  "sculk sensor": "A block that detects vibrations and emits redstone signals.",
  "sculk vein": "A thin, vein‑like block that spreads over surfaces.",
  "reinforced deepslate": "An unbreakable block found in ancient cities.",
  "crying obsidian": "A glowing obsidian block found in ruined portals. Used to craft respawn anchors.",
  "glowstone": "A luminous block found in the Nether. Drops glowstone dust.",
  "sea lantern": "A bright light source found in ocean monuments.",
  "prismarine": "A decorative block found in ocean monuments.",
  "prismarine bricks": "A variant of prismarine.",
  "dark prismarine": "A darker variant of prismarine.",
  "concrete": "A solid, brightly colored block made from concrete powder and water.",
  "concrete powder": "A powder that becomes concrete when placed in water.",
  "terracotta": "A baked clay block. Comes in many colors.",
  "glazed terracotta": "Decorative terracotta with patterns. Smelted from terracotta.",
  "glass": "A transparent block. Made from sand.",
  "stained glass": "Glass colored with dye.",
  "glass pane": "A thinner version of glass.",
  "stained glass pane": "Thin stained glass.",
  "sand": "A loose block found in deserts and beaches. Can be smelted into glass.",
  "red sand": "A red variant of sand found in badlands.",
  "gravel": "A loose block that can drop flint when mined.",
  "dirt": "A common block. Grass grows on it.",
  "coarse dirt": "Dirt that does not grow grass.",
  "podzol": "A dirt variant found in old growth taiga. Grass does not grow.",
  "grass block": "A block with grass on top. Spreads over dirt.",
  "mycelium": "A purple‑colored block found in mushroom fields. Spreads over dirt.",
  "snow block": "A block of snow. Made from snowballs.",
  "ice": "A slippery block found in snowy biomes. Melts near light sources.",
  "packed ice": "A solid ice block that does not melt.",
  "blue ice": "A very slippery ice found in icebergs.",
  "brick block": "A block made of bricks.",
  "nether brick": "A brick block made from netherrack.",
  "red nether brick": "A red variant of nether brick.",
  "stone": "A common solid block. Cobblestone can be smelted into stone.",
  "cobblestone": "A common block dropped when mining stone.",
  "mossy cobblestone": "Cobblestone with moss. Found in dungeons.",
  "stone bricks": "A decorative block made from stone.",
  "mossy stone bricks": "Stone bricks with moss.",
  "cracked stone bricks": "Damaged stone bricks.",
  "chiseled stone bricks": "Carved stone bricks.",
  "granite": "A pinkish stone found underground.",
  "diorite": "A white‑gray stone found underground.",
  "andesite": "A gray stone found underground.",
  "smooth stone": "Stone smelted from regular stone.",
  "smooth sandstone": "Smooth version of sandstone.",
  "sandstone": "A block made from sand. Found in deserts.",
  "cut sandstone": "A decorative sandstone.",
  "chiseled sandstone": "Carved sandstone.",
  "red sandstone": "A red variant of sandstone.",
  "cut red sandstone": "Decorative red sandstone.",
  "chiseled red sandstone": "Carved red sandstone.",
  "blackstone": "A dark stone found in the Nether. Used as a building block.",
  "gilded blackstone": "Blackstone with gold particles. Sometimes drops gold nuggets.",
  "basalt": "A volcanic rock found in the Nether.",
  "polished basalt": "Smooth basalt.",
  "smooth basalt": "A dark smooth rock.",
  "obsidian": "A very hard block formed from water and lava. Used for portals.",
  "crying obsidian": "Glowing obsidian. Used for respawn anchors.",
  "bedrock": "An unbreakable block at the bottom of the world.",
  "end stone": "A stone found in the End.",
  "purpur block": "A decorative block found in End cities.",
  "purpur pillar": "A pillared variant of purpur.",
  "purpur stairs": "Stairs made of purpur.",
  "purpur slab": "Slabs of purpur.",
  "end rod": "A light source found in End cities. Emits light upward.",
  "dragon head": "A decorative head of the Ender Dragon. Found on End ships.",
  "shulker box": "A portable chest that retains its contents when broken.",
  "barrel": "A storage block that can hold items. Acts like a chest.",
  "composter": "A block that turns organic items into bonemeal.",
  "loom": "A block used to create patterns on banners.",
  "cartography table": "A block used to clone, zoom, and lock maps.",
  "fletching table": "A villager workstation for fletchers.",
  "grindstone": "A block used to repair and disenchant items.",
  "stonecutter": "A block used to craft stone blocks more efficiently.",
  "crafting table": "A block used to craft items with a 3x3 grid.",
  "furnace": "A block used to smelt and cook items.",
  "blast furnace": "A faster furnace that smelts ore and metal.",
  "smoker": "A fast furnace that cooks food.",
  "brewing stand": "A block used to brew potions.",
  "anvil": "A block used to repair, rename, and combine enchanted items.",
  "enchanting table": "A block used to enchant items using XP and lapis.",
  "bookshelf": "A block that increases the enchantment level of an enchanting table.",
  "lectern": "A block that holds a book. Used by librarians.",
  "chest": "A storage block with 27 slots.",
  "trapped chest": "A chest that emits a redstone signal when opened.",
  "ender chest": "A chest that shares inventory across all dimensions.",
  "bed": "A block used to sleep and set spawn point.",
  "spawner": "A block that spawns mobs in a radius.",
  "beacon": "A block that gives status effects to players within its range.",
  "conduit": "A block that gives underwater buffs when activated.",
  "respawn anchor": "A block used to set spawn point in the Nether.",
  "lodestone": "A block that compasses point to when clicked.",
  "bell": "A block that rings when used. Found in villages.",
  "campfire": "A block that cooks food and provides light.",
  "soul campfire": "A blue campfire made with soul soil.",
  "lantern": "A hanging light source.",
  "soul lantern": "A blue hanging light source.",
  "torch": "A basic light source. Crafted from coal and stick.",
  "soul torch": "A blue torch made from soul soil.",
  "redstone dust": "A powder that transmits redstone power.",
  "redstone torch": "A torch that provides redstone power.",
  "redstone repeater": "A block that extends redstone signals.",
  "redstone comparator": "A block that compares redstone signals.",
  "piston": "A block that pushes other blocks.",
  "sticky piston": "A piston that also pulls blocks back.",
  "slime block": "A bouncy block used in redstone contraptions.",
  "honey block": "A sticky block made from honey.",
  "hopper": "A block that moves items into containers.",
  "dropper": "A block that drops items when powered.",
  "dispenser": "A block that shoots or drops items when powered.",
  "observer": "A block that detects block updates.",
  "tripwire hook": "A hook used to create tripwires.",
  "daylight detector": "A block that emits redstone based on daylight.",
  "pressure plate": "A plate that triggers redstone when stepped on.",
  "weighted pressure plate": "A plate that triggers based on number of entities.",
  "button": "A switch that gives a redstone pulse when pressed.",
  "lever": "A switch that toggles redstone power.",
  "trapdoor": "A horizontal door.",
  "iron trapdoor": "A horizontal door made of iron.",
  "fence": "A wall block that connects to others.",
  "fence gate": "A gate that opens and closes.",
  "wall": "A wall block that creates a barrier.",
  "door": "A vertical door.",
  "iron door": "A vertical door made of iron.",
  "chest boat": "A boat with a chest.",
  "soul soil": "A block found in the Nether. Used to create soul fire.",
  "soul sand": "A block found in the Nether. Slows movement.",
  "nylium": "A fungus‑covered stone found in Nether biomes.",
  "warped wart block": "A block found in warped forests.",
  "nether wart block": "A block found in crimson forests.",
  "shroomlight": "A glowing block found in crimson and warped forests.",
  "weeping vines": "Vines that grow downward in the Nether.",
  "twisting vines": "Vines that grow upward in the Nether.",
  "crimson roots": "Roots found in crimson forests.",
  "warped roots": "Roots found in warped forests.",
  "crimson fungus": "A fungus found in crimson forests.",
  "warped fungus": "A fungus found in warped forests.",
  "nether wart": "A plant grown on soul sand for brewing.",
  "cobweb": "A block that slows entities.",
  "snow": "A thin layer of snow.",
  "vine": "A climbing plant.",
  "lily pad": "A floating plant that can be walked on.",
  "seagrass": "A plant found underwater.",
  "kelp": "A plant that grows underwater.",
  "bamboo": "A fast‑growing plant.",
  "sugar cane": "A plant that grows near water.",
  "cactus": "A plant found in deserts.",
  "flower": "A colorful plant. Many varieties.",
  "tall grass": "A grass plant.",
  "fern": "A fern plant.",
  "dead bush": "A dry bush.",
  "pumpkin": "A fruit block that can be carved.",
  "carved pumpkin": "A carved pumpkin that can be worn.",
  "jack o'lantern": "A lit pumpkin.",
  "melon": "A fruit block that drops melon slices.",
  "hay bale": "A block of dried wheat.",
  "dried kelp block": "A block of dried kelp used as fuel.",
  "bee nest": "A nest containing bees.",
  "beehive": "A crafted home for bees.",
  "honeycomb": "A wax item used to make candles and waxed copper.",
  "candle": "A light source that can be colored and placed on cakes.",
  "cake": "A food block that can be eaten in slices.",
  "tnt": "A block that explodes when ignited.",
  "slab": "A half‑height block.",
  "stairs": "Stair blocks.",
  "moss block": "A green block that spreads.",
  "moss carpet": "A thin moss layer.",
  "azalea": "A plant found in lush caves.",
  "flowering azalea": "A blooming azalea.",
  "rooted dirt": "Dirt with roots.",
  "hanging roots": "Roots that hang from the ceiling.",
  "spore blossom": "A decorative block that emits particles.",
  "big dripleaf": "A large leaf that can hold entities.",
  "small dripleaf": "A small leaf.",
  "glow lichen": "A glowing plant that covers surfaces.",

  // ─── ITEMS ────────────────────────────────────────────────────────────────
  "diamond": "A precious gem used for tools, armor, and enchantments.",
  "emerald": "A green gem used for trading with villagers.",
  "netherite ingot": "A strong material made from netherite scrap and gold.",
  "netherite scrap": "A material smelted from ancient debris.",
  "gold ingot": "A yellow metal used for crafting and trading.",
  "iron ingot": "A common metal used for tools, armor, and crafting.",
  "copper ingot": "A metal used for building and crafting.",
  "coal": "A fuel and crafting material.",
  "charcoal": "A fuel made from wood.",
  "raw iron": "Raw iron ore dropped from iron ore.",
  "raw gold": "Raw gold ore.",
  "raw copper": "Raw copper ore.",
  "stick": "A basic material used in many recipes.",
  "feather": "Dropped by chickens. Used for arrows.",
  "flint": "Dropped from gravel. Used for flint and steel.",
  "flint and steel": "A tool used to light fires and portals.",
  "saddle": "A tool used to ride horses and pigs.",
  "leather": "Obtained from cows. Used for armor and books.",
  "string": "Dropped by spiders. Used for bows and leads.",
  "paper": "Made from sugar cane. Used for books and maps.",
  "book": "Made from paper and leather. Used for crafting and enchanting.",
  "written book": "A book with custom text.",
  "enchanted book": "A book with an enchantment.",
  "name tag": "An item used to name mobs.",
  "lead": "Used to leash mobs.",
  "bucket": "Holds liquids and milk.",
  "water bucket": "A bucket filled with water.",
  "lava bucket": "A bucket filled with lava.",
  "milk bucket": "A bucket filled with milk.",
  "bowl": "Used to hold soup and stew.",
  "mushroom stew": "A food made from mushrooms.",
  "suspicious stew": "A stew with a random effect.",
  "beetroot soup": "A food made from beetroot.",
  "rabbit stew": "A food made from rabbit and vegetables.",
  "bread": "A food made from wheat.",
  "cooked porkchop": "Cooked pork, restores hunger.",
  "cooked beef": "Cooked steak.",
  "cooked chicken": "Cooked chicken.",
  "cooked mutton": "Cooked mutton.",
  "cooked rabbit": "Cooked rabbit.",
  "cooked cod": "Cooked fish.",
  "cooked salmon": "Cooked salmon.",
  "baked potato": "Cooked potato.",
  "golden apple": "An apple that gives temporary buffs.",
  "enchanted golden apple": "A very powerful golden apple with regeneration.",
  "golden carrot": "A carrot with gold. High saturation.",
  "potion": "A consumable that gives effects.",
  "splash potion": "A potion that can be thrown.",
  "lingering potion": "A potion that creates a lingering cloud.",
  "glass bottle": "Used to collect water and brew potions.",
  "dragon's breath": "Collected from the Ender Dragon's breath attack.",
  "nether wart": "A plant used in brewing.",
  "glistering melon": "Used to brew healing potions.",
  "magma cream": "Used to brew fire resistance potions.",
  "ghast tear": "Used to brew regeneration potions.",
  "blaze powder": "Used to brew potions and craft Eyes of Ender.",
  "fermented spider eye": "Used to brew negative potions.",
  "rabbit's foot": "Used to brew leaping potions.",
  "pufferfish": "Used to brew water breathing potions.",
  "turtle shell": "Used to brew turtle master potions.",
  "phantom membrane": "Used to brew slow falling potions.",
  "slimeball": "Used to make sticky pistons and leads.",
  "ender pearl": "Used to teleport and craft Eyes of Ender.",
  "eye of ender": "Used to locate strongholds and activate the End portal.",
  "shield": "A tool that blocks attacks.",
  "totem of undying": "An item that prevents death once.",
  "elytra": "Wings that allow flight.",
  "trident": "A weapon that can be thrown.",
  "mace": "A heavy weapon from the trial chambers.",
  "brush": "A tool used to uncover items in suspicious blocks.",
  "spyglass": "A tool used to zoom in.",
  "clock": "Shows the time.",
  "compass": "Points to your spawn point.",
  "recovery compass": "Points to your last death point.",
  "map": "Shows a view of the terrain.",
  "empty map": "A blank map.",
  "filled map": "A map with terrain data.",
  "fishing rod": "Used to catch fish and items.",
  "carrot": "A vegetable used as food and for breeding.",
  "potato": "A vegetable used for food and cooking.",
  "baked potato": "Cooked potato.",
  "poisonous potato": "A potato that can poison.",
  "beetroot": "A vegetable used for food.",
  "melon slice": "A fruit slice.",
  "apple": "A fruit found on trees.",
  "sweet berries": "A berry found in taiga.",
  "glow berries": "Glowing berries found in lush caves.",
  "chorus fruit": "A fruit that teleports you when eaten.",
  "chorus flower": "A flower found on End islands.",
  "dragon egg": "A trophy from the Ender Dragon.",
  "diamond hoe": "A hoe made of diamond.",
  "diamond shovel": "A shovel made of diamond.",
  "diamond axe": "An axe made of diamond.",
  "diamond pickaxe": "A pickaxe made of diamond.",
  "diamond sword": "A sword made of diamond.",
  "iron sword": "A sword made of iron.",
  "iron pickaxe": "A pickaxe made of iron.",
  "iron shovel": "A shovel made of iron.",
  "iron axe": "An axe made of iron.",
  "iron hoe": "A hoe made of iron.",
  "netherite sword": "A sword made of netherite.",
  "netherite pickaxe": "A pickaxe made of netherite.",
  "netherite shovel": "A shovel made of netherite.",
  "netherite axe": "An axe made of netherite.",
  "netherite hoe": "A hoe made of netherite.",
  "chainmail helmet": "A helmet made of chain.",
  "chainmail chestplate": "Chainmail chestplate.",
  "chainmail leggings": "Chainmail leggings.",
  "chainmail boots": "Chainmail boots.",
  "leather helmet": "A helmet made of leather.",
  "leather chestplate": "Leather chestplate.",
  "leather leggings": "Leather leggings.",
  "leather boots": "Leather boots.",
  "iron helmet": "Iron helmet.",
  "iron chestplate": "Iron chestplate.",
  "iron leggings": "Iron leggings.",
  "iron boots": "Iron boots.",
  "golden helmet": "Golden helmet.",
  "golden chestplate": "Golden chestplate.",
  "golden leggings": "Golden leggings.",
  "golden boots": "Golden boots.",
  "diamond helmet": "Diamond helmet.",
  "diamond chestplate": "Diamond chestplate.",
  "diamond leggings": "Diamond leggings.",
  "diamond boots": "Diamond boots.",
  "netherite helmet": "Netherite helmet.",
  "netherite chestplate": "Netherite chestplate.",
  "netherite leggings": "Netherite leggings.",
  "netherite boots": "Netherite boots.",
  "turtle shell helmet": "A helmet made from turtle shells.",
  "carrot on a stick": "Used to control pigs.",
  "warped fungus on a stick": "Used to control striders.",
  "music disc": "A disc that plays music.",
  "chest minecart": "A minecart with a chest.",
  "furnace minecart": "A minecart that moves with fuel.",
  "hopper minecart": "A minecart with a hopper.",
  "tnt minecart": "A minecart with TNT.",
  "rail": "A track for minecarts.",
  "powered rail": "A rail that speeds up minecarts.",
  "detector rail": "A rail that emits redstone.",
  "activator rail": "A rail that activates minecarts.",
  "minecart": "A vehicle for rails.",

  // ─── MOBS ──────────────────────────────────────────────────────────────────
  "zombie": "A slow, hostile mob that burns in sunlight. Drops rotten flesh.",
  "zombie villager": "A villager that has been infected. Can be cured.",
  "husk": "A zombie variant found in deserts. Does not burn in sunlight.",
  "drowned": "A zombie variant found in water. Can drop tridents.",
  "skeleton": "A hostile archer that burns in sunlight. Drops bones and arrows.",
  "stray": "A skeleton variant found in snowy biomes. Shoots slowness arrows.",
  "creeper": "A hostile mob that explodes when near players. Drops gunpowder.",
  "spider": "A hostile mob that climbs walls. Drops string and spider eyes.",
  "cave spider": "A smaller, poisonous spider found in mineshafts.",
  "slime": "A bouncy mob that splits into smaller sizes. Drops slimeballs.",
  "magma cube": "A Nether slime that splits and drops magma cream.",
  "ghast": "A large floating Nether mob that shoots fireballs. Drops ghast tears.",
  "blaze": "A Nether mob that shoots fireballs. Drops blaze rods.",
  "wither skeleton": "A skeleton variant in Nether fortresses. Drops coal and bones.",
  "enderman": "A tall, teleporting mob that is neutral unless looked at. Drops ender pearls.",
  "endermite": "A small mob that spawns when an enderman teleports.",
  "shulker": "A mob in End cities that shoots homing bullets. Drops shulker shells.",
  "warden": "A blind, powerful mob in the deep dark that senses vibrations.",
  "villager": "A passive mob that trades items. Has professions.",
  "iron golem": "A large mob that protects villagers.",
  "snow golem": "A mob that throws snowballs.",
  "wandering trader": "A merchant that appears randomly with llamas.",
  "llama": "A passive mob that can carry chests. Spits when angered.",
  "trader llama": "A llama that accompanies wandering traders.",
  "polar bear": "A neutral mob in snowy biomes.",
  "panda": "A passive mob in jungles. Comes in different personalities.",
  "fox": "A passive mob that can hold items and sleep during day.",
  "horse": "A tameable mob that can be ridden.",
  "donkey": "A horse variant that can carry a chest.",
  "mule": "A hybrid of horse and donkey. Cannot breed.",
  "skeleton horse": "A horse that spawns during thunderstorms.",
  "zombie horse": "A zombie horse. Not naturally spawning.",
  "cow": "A passive mob that drops leather and beef.",
  "sheep": "A passive mob that drops wool and mutton.",
  "pig": "A passive mob that drops porkchops.",
  "chicken": "A passive mob that drops feathers and chicken.",
  "rabbit": "A passive mob that drops rabbit hide and rabbit foot.",
  "turtle": "A passive mob that drops turtle shells when bred.",
  "ocelot": "A passive mob in jungles. Can be tamed with fish.",
  "cat": "A tamed ocelot variant. Drops string when given items?",
  "parrot": "A passive mob that can mimic sounds.",
  "bat": "A passive mob that spawns in caves.",
  "bee": "A passive mob that pollinates plants and drops honey.",
  "wolf": "A neutral mob that can be tamed with bones.",
  "dolphin": "A neutral mob that gives speed buff.",
  "pufferfish": "A passive mob that puffs up and poisons.",
  "cod": "A passive fish.",
  "salmon": "A passive fish.",
  "tropical fish": "A colorful fish.",
  "squid": "A passive mob that drops ink sacs.",
  "glow squid": "A glowing squid that drops glow ink sacs.",
  "strider": "A passive mob that walks on lava in the Nether.",
  "hoglin": "A hostile mob in crimson forests. Drops porkchops.",
  "zombified piglin": "A neutral Nether mob. Drops gold nuggets.",
  "piglin": "A neutral mob that trades and attacks without gold armor.",
  "piglin brute": "A hostile piglin found in bastions.",
  "vex": "A small flying mob summoned by evokers.",
  "evoker": "A hostile illager that summons fangs and vexes.",
  "vindicator": "A hostile illager with an axe.",
  "pillager": "A hostile illager with a crossbow.",
  "illusioner": "A hostile illager that creates illusions.",
  "ravager": "A large, hostile illager beast.",
  "witch": "A hostile mob that throws potions.",
  "guardian": "A hostile underwater mob that shoots lasers.",
  "elder guardian": "A larger guardian that gives mining fatigue.",
  "phantom": "A flying mob that attacks players who haven't slept.",
  "ender dragon": "The final boss. Lives in the End.",
  "wither": "A boss that can be summoned. Drops a nether star.",

  // ─── BIOMES ────────────────────────────────────────────────────────────────
  "plains": "A flat biome with grass and flowers.",
  "sunflower plains": "A plains biome with sunflowers.",
  "desert": "A hot biome with sand, cacti, and dead bushes.",
  "badlands": "A mesa biome with red sand and terracotta.",
  "wooded badlands": "Badlands with oak trees.",
  "savanna": "A warm biome with acacia trees.",
  "savanna plateau": "A raised savanna biome.",
  "windswept savanna": "A hilly savanna.",
  "taiga": "A cold biome with spruce trees.",
  "snowy taiga": "A snowy version of taiga.",
  "old growth taiga": "A taiga with giant spruce trees.",
  "old growth pine taiga": "A taiga with giant pine trees.",
  "forest": "A biome with many oak and birch trees.",
  "flower forest": "A forest with many flowers.",
  "birch forest": "A forest with only birch trees.",
  "old growth birch forest": "A birch forest with tall birches.",
  "dark forest": "A dense forest with dark oak trees.",
  "jungle": "A lush biome with large trees and vines.",
  "bamboo jungle": "A jungle with bamboo.",
  "sparse jungle": "A less dense jungle.",
  "swamp": "A wet biome with muddy water and vines.",
  "mangrove swamp": "A swamp with mangrove trees.",
  "mushroom fields": "A rare biome with mushrooms and mycelium.",
  "snowy plains": "A cold biome with snow.",
  "ice spikes": "A biome with large ice spikes.",
  "snowy taiga": "A snowy forest.",
  "snowy beach": "A beach covered in snow.",
  "cold ocean": "A cold ocean biome.",
  "deep cold ocean": "A deep cold ocean.",
  "frozen ocean": "An ocean covered in ice.",
  "deep frozen ocean": "A deep frozen ocean.",
  "ocean": "A large body of water.",
  "deep ocean": "A deep ocean.",
  "warm ocean": "A warm ocean with coral reefs.",
  "lukewarm ocean": "A lukewarm ocean.",
  "deep lukewarm ocean": "A deep lukewarm ocean.",
  "river": "A freshwater river.",
  "frozen river": "A frozen river.",
  "beach": "A sandy beach.",
  "stony shore": "A rocky shore.",
  "snowy slopes": "A mountain slope with snow.",
  "jagged peaks": "A jagged mountain peak.",
  "frozen peaks": "A frozen mountain peak.",
  "stony peaks": "A rocky mountain peak.",
  "meadow": "A flat, flowery mountain biome.",
  "grove": "A snowy mountain slope with spruce trees.",
  "cherry grove": "A biome with cherry trees.",
  "lush caves": "A cave biome with vegetation and moss.",
  "dripstone caves": "A cave biome with dripstone formations.",
  "deep dark": "A dark biome with sculk blocks and wardens.",
  "nether wastes": "A barren Nether biome.",
  "crimson forest": "A red Nether forest with crimson trees.",
  "warped forest": "A blue Nether forest with warped trees.",
  "soul sand valley": "A Nether biome with soul sand and fossils.",
  "basalt deltas": "A Nether biome with basalt and lava.",
  "the end": "A dimension with floating islands and the dragon.",
  "end highlands": "The main End islands.",
  "end midlands": "The middle End islands.",
  "end barrens": "The barren outer End islands.",
  "small end islands": "Small end islands.",

  // ─── STRUCTURES ──────────────────────────────────────────────────────────
  "village": "A generated structure with villagers and buildings.",
  "desert temple": "A pyramid in the desert with a hidden chest.",
  "jungle temple": "A stone temple in the jungle with traps.",
  "witch hut": "A small house in swamps containing a witch.",
  "igloo": "A snow house that can have a basement.",
  "ocean monument": "A large underwater structure with guardians.",
  "woodland mansion": "A large mansion in dark forests with illagers.",
  "stronghold": "A underground structure containing the End portal.",
  "end city": "A structure in the End with loot and shulkers.",
  "end ship": "A ship with an elytra and dragon head.",
  "nether fortress": "A large structure in the Nether with blazes.",
  "bastion remnant": "A Nether structure with piglins and gold.",
  "ruined portal": "A ruined Nether portal with crying obsidian.",
  "shipwreck": "A shipwreck in oceans with loot.",
  "buried treasure": "A chest buried in beaches.",
  "mineshaft": "An underground structure with rails and chests.",
  "pillager outpost": "A structure with pillagers and a banner.",
  "ancient city": "A large structure in the deep dark with sculk.",
  "trail ruins": "A archaeological site with suspicious blocks.",
  "trial chambers": "A new structure with mob spawners and rewards.",

  // ─── ENCHANTMENTS ────────────────────────────────────────────────────────
  "protection": "Reduces all damage taken.",
  "fire protection": "Reduces fire damage.",
  "blast protection": "Reduces explosion damage.",
  "projectile protection": "Reduces projectile damage.",
  "feather falling": "Reduces fall damage.",
  "respiration": "Increases underwater breathing time.",
  "aqua affinity": "Speeds up underwater mining.",
  "thorns": "Damages attackers when hit.",
  "depth strider": "Allows faster swimming.",
  "frost walker": "Creates ice under your feet.",
  "soul speed": "Increases speed on soul sand and soul soil.",
  "sharpness": "Increases melee damage.",
  "smite": "Deals extra damage to undead mobs.",
  "bane of arthropods": "Deals extra damage to arthropods.",
  "knockback": "Knocks back enemies.",
  "fire aspect": "Sets enemies on fire.",
  "looting": "Increases mob drop rates.",
  "sweeping edge": "Damages nearby mobs.",
  "efficiency": "Speeds up mining.",
  "fortune": "Increases drops from ores and plants.",
  "silk touch": "Allows you to collect blocks in their original form.",
  "unbreaking": "Increases durability.",
  "mending": "Repairs the item using XP.",
  "curse of binding": "Prevents removing the item.",
  "curse of vanishing": "Item disappears on death.",
  "power": "Increases bow damage.",
  "punch": "Knocks enemies back on bow shot.",
  "flame": "Sets arrows on fire.",
  "infinity": "Shoots infinite arrows (requires one arrow).",
  "quick charge": "Speeds up crossbow reload.",
  "multishot": "Fires three arrows at once.",
  "piercing": "Arrows pierce through mobs.",
  "loyalty": "Trident returns to you.",
  "impaling": "Deals extra damage to aquatic mobs.",
  "riptide": "Allows you to launch with a trident.",
  "channeling": "Summons lightning during thunderstorms.",
  "mace": "A new weapon enchantment for the mace.",

  // ─── POTIONS / EFFECTS ─────────────────────────────────────────────────
  "swiftness": "Increases movement speed.",
  "slowness": "Decreases movement speed.",
  "haste": "Increases mining speed.",
  "mining fatigue": "Decreases mining speed.",
  "strength": "Increases attack damage.",
  "instant health": "Heals health instantly.",
  "instant damage": "Damages health instantly.",
  "jump boost": "Increases jump height.",
  "nausea": "Causes a distorted screen.",
  "regeneration": "Restores health over time.",
  "resistance": "Reduces damage taken.",
  "fire resistance": "Immunity to fire and lava.",
  "water breathing": "Allows breathing underwater.",
  "invisibility": "Makes you invisible.",
  "blindness": "Reduces your vision.",
  "night vision": "Allows seeing in the dark.",
  "hunger": "Increases hunger drain.",
  "weakness": "Reduces attack damage.",
  "poison": "Damages health over time.",
  "wither": "Damages health over time, bypasses armor.",
  "health boost": "Increases max health.",
  "absorption": "Gives extra health (golden hearts).",
  "saturation": "Restores hunger.",
  "glowing": "Outlines the entity.",
  "levitation": "Lifts the entity upward.",
  "luck": "Increases loot quality.",
  "bad luck": "Decreases loot quality.",
  "slow falling": "Reduces fall speed.",
  "conduit power": "Gives water breathing, night vision, and haste underwater.",
  "dolphin's grace": "Speeds up swimming.",

  // ─── DIMENSIONS ──────────────────────────────────────────────────────────
  "overworld": "The main dimension. Has biomes, caves, and all standard resources.",
  "nether": "A hellish dimension with lava, hostile mobs, and rare resources.",
  "the end": "A dimension with floating islands, the Ender Dragon, and End cities.",

  // ─── GAME MECHANICS ─────────────────────────────────────────────────────
  "mining": "Breaking blocks to gather resources. Requires the right tool.",
  "smelting": "Heating items in a furnace to transform them (e.g., ore to ingot).",
  "crafting": "Combining items in a grid to create new items.",
  "enchanting": "Using XP and lapis to add enchantments to gear.",
  "brewing": "Creating potions with ingredients in a brewing stand.",
  "trading": "Exchanging emeralds and items with villagers.",
  "farming": "Growing crops to harvest food and materials.",
  "breeding": "Using food to breed passive mobs.",
  "taming": "Using items to tame mobs (e.g., wolves, cats).",
  "fishing": "Using a fishing rod to catch fish and items.",
  "exploring": "Traveling to discover biomes, structures, and resources.",
  "combat": "Fighting mobs and players. Uses weapons and armor.",
  "building": "Placing blocks to create structures.",
  "redstone": "Using redstone dust and components to create circuits.",
  "flying": "Using elytra or creative mode to fly.",
  "swimming": "Moving through water. Faster with depth strider.",
  "climbing": "Using ladders, vines, and scaffolding.",
  "sneaking": "Crouching to avoid falling and to be quieter.",
  "sprinting": "Running faster, consumes hunger faster.",
  "jumping": "Jumping to clear gaps. Height depends on hunger.",
  "falling": "Taking damage from falls. Feather falling reduces it.",
  "dying": "When health reaches 0. Drop items and lose XP.",
  "sleeping": "Using a bed at night to skip to day and set spawn.",
  "xp": "Experience points gained from activities. Used for enchanting.",

  // ─── STATUS EFFECTS ─────────────────────────────────────────────────────
  "absorption": "Temporary extra health (golden hearts).",
  "bad omen": "Triggers a raid when entering a village.",
  "blindness": "Reduces visibility.",
  "conduit power": "Underwater buffs.",
  "darkness": "Lowers visibility in the deep dark.",
  "dolphin's grace": "Increases swimming speed.",
  "fire resistance": "Immunity to fire.",
  "glowing": "Outlines the entity.",
  "haste": "Increases mining speed.",
  "health boost": "Increases max health.",
  "hero of the village": "Gives discounts when trading.",
  "hunger": "Increases food consumption.",
  "instant damage": "Deals damage immediately.",
  "instant health": "Heals immediately.",
  "invisibility": "Makes you invisible.",
  "jump boost": "Increases jump height.",
  "levitation": "Lifts upward.",
  "luck": "Improves loot drops.",
  "mining fatigue": "Slows mining speed.",
  "nausea": "Causes screen distortion.",
  "night vision": "Allows seeing in the dark.",
  "poison": "Deals damage over time.",
  "regeneration": "Restores health over time.",
  "resistance": "Reduces damage.",
  "saturation": "Restores hunger.",
  "slow falling": "Slows fall speed.",
  "slowness": "Reduces movement speed.",
  "strength": "Increases attack damage.",
  "swiftness": "Increases movement speed.",
  "water breathing": "Allows breathing underwater.",
  "weakness": "Reduces attack damage.",
  "wither": "Deals damage over time, bypasses armor.",
};

// ─────────────────────────────────────────────────────────────────────────────
// LOOKUP FUNCTION
// ─────────────────────────────────────────────────────────────────────────────

function lookupWiki(topic) {
  const key = topic.toLowerCase().trim();
  // Try exact match
  if (WIKI[key]) return WIKI[key];
  // Try singular (remove trailing 's')
  if (key.endsWith('s')) {
    const singular = key.slice(0, -1);
    if (WIKI[singular]) return WIKI[singular];
  }
  // Try removing "the " prefix
  if (key.startsWith('the ')) {
    const withoutThe = key.slice(4);
    if (WIKI[withoutThe]) return WIKI[withoutThe];
  }
  return null;
}

// ─────────────────────────────────────────────────────────────────────────────
// HANDLER REGEXES AND FUNCTIONS
// ─────────────────────────────────────────────────────────────────────────────

// 1. Generic "what is X" – uses the wiki lookup
const WHAT_IS_WIKI_REGEX = /\bwhat is (a|an|the)?\s*([a-zA-Z][a-zA-Z0-9_ ]{2,40})\??$/i;
function whatIsWikiResponse(msg, p) {
  const match = msg.match(WHAT_IS_WIKI_REGEX);
  if (!match) return null;
  const topic = match[2].trim();
  const entry = lookupWiki(topic);
  if (!entry) return null;

  const R = [
    [`${topic}: ${entry}`, `That's ${topic}. ${entry}`, `In Minecraft, ${topic} is ${entry}`],
    [`${topic} – ${entry}`, `${topic} is ${entry}`, `Yes, ${topic}: ${entry}`],
    [`${topic} is ${entry} – but it won't save you.`, `${topic}: ${entry} – interesting, right?`, `${topic} is ${entry}. Not that it matters.`],
    [`${topic} – ${entry}. You should know that by now.`, `${topic} is ${entry}. It won't change anything.`, `${topic}: ${entry}. That's what it is.`],
    [`${topic} is ${entry}. I'm glad you're learning.`, `${topic} – I know it well. ${entry}`, `${topic}: ${entry}. That's the truth.`],
    [`${topic} – ${entry}. I've known that for a long time.`, `${topic} is ${entry}. And that's all you need to know.`],
  ];
  return pick(ph(R, p));
}

// 2. Generic "how to make X" – tries to find a recipe, falls back to generic
const HOW_TO_MAKE_WIKI_REGEX = /\bhow (to|do i) (make|craft|build)\s+([a-zA-Z][a-zA-Z0-9_ ]{2,40})\??$/i;
function howToMakeWikiResponse(msg, p) {
  const match = msg.match(HOW_TO_MAKE_WIKI_REGEX);
  if (!match) return null;
  const item = match[3].trim();
  // Try to give a generic crafting answer based on category
  const entry = lookupWiki(item);
  if (entry) {
    const R = [
      [`To craft ${item}, you need the right materials. It's used for ${entry}`, `Crafting ${item} requires specific ingredients. Its purpose: ${entry}`, `${item} is made with common resources. It's ${entry}`],
      [`${item} is crafted. It's ${entry}`, `You can craft ${item} with the right recipe. It's ${entry}`, `${item} – it's used for ${entry}`],
      [`Crafting ${item} won't stop the end. It's ${entry}`, `${item} is a craftable item. It's ${entry}`, `You'll need to craft ${item} – it's ${entry}`],
      [`${item} is crafted. That's it.`, `Craft ${item} if you must. It's ${entry}`, `${item} – you know the recipe.`],
      [`I like that you're crafting ${item}. It's ${entry}`, `Craft ${item} – it's useful.`, `${item} is a good craft.`],
      [`Crafting ${item} is a skill. It's ${entry}`, `${item} – it's just a craft.`],
    ];
    return pick(ph(R, p));
  }
  // Generic fallback
  const R2 = [
    [`I can't give a specific recipe for ${item}, but you can find it online or in a recipe book.`, `${item} requires materials. Check the recipe book.`, `Crafting ${item} – you'll need to experiment.`],
    [`${item} is craftable. Not sure of the exact recipe.`, `${item} – you'll figure it out.`, `I'd need more details on ${item}.`],
    [`Crafting ${item} might not help.`, `${item} is a mystery to me.`, `${item} – good luck crafting it.`],
    [`${item} – it's not worth it.`, `Craft ${item} if you want.`, `${item} is just a craft.`],
    [`I like that you're curious about ${item}.`, `Craft ${item} – I'm curious too.`, `${item} is interesting.`],
    [`${item} – I've seen it crafted before.`, `${item} is a craft.`],
  ];
  return pick(ph(R2, p));
}

// 3. Generic "where to find X"
const WHERE_TO_FIND_WIKI_REGEX = /\bwhere (can|do i) find (a|an|the)?\s*([a-zA-Z][a-zA-Z0-9_ ]{2,40})\??$/i;
function whereToFindWikiResponse(msg, p) {
  const match = msg.match(WHERE_TO_FIND_WIKI_REGEX);
  if (!match) return null;
  const item = match[3].trim();
  const entry = lookupWiki(item);
  if (entry) {
    const R = [
      [`You can find ${item} in various places. It's ${entry}`, `${item} is found in specific biomes or structures. It's ${entry}`, `${item} – you'll find it if you explore.`],
      [`${item} is out there. ${entry}`, `Look for ${item} in the usual spots. ${entry}`, `${item} – it's a resource. ${entry}`],
      [`Finding ${item} might not save you. It's ${entry}`, `${item} is somewhere. ${entry}`, `${item} – you'll know when you see it.`],
      [`${item} is always there. ${entry}`, `${item} is a distraction. ${entry}`, `${item} – just keep looking.`],
      [`I like that you're searching for ${item}. It's ${entry}`, `${item} is worth the effort.`, `${item} – you'll find it.`],
      [`${item} – I've found it many times. ${entry}`, `${item} is just a thing.`],
    ];
    return pick(ph(R, p));
  }
  // Generic fallback
  const R2 = [
    [`I don't have specific coordinates for ${item}, but explore caves, biomes, or structures.`, `${item} can be found in the world.`, `Search for ${item} in the usual locations.`],
    [`${item} is out there. You'll find it.`, `${item} – not sure exactly where.`, `${item} – look around.`],
    [`Finding ${item} might take time.`, `${item} – it's hidden.`, `${item} – good luck.`],
    [`${item} – you'll find it eventually.`, `${item} is a treasure.`, `${item} – it's everywhere.`],
    [`I like that you're looking for ${item}.`, `${item} – I hope you find it.`, `${item} is an adventure.`],
    [`${item} – I've found it before.`, `${item} is a journey.`],
  ];
  return pick(ph(R2, p));
}

// ─────────────────────────────────────────────────────────────────────────────
// EXPORT – all new handlers
// ─────────────────────────────────────────────────────────────────────────────

export {
  WHAT_IS_WIKI_REGEX, whatIsWikiResponse,
  HOW_TO_MAKE_WIKI_REGEX, howToMakeWikiResponse,
  WHERE_TO_FIND_WIKI_REGEX, whereToFindWikiResponse,
};