// ─────────────────────────────────────────────────────────────────────────────
// verity_responses_7.js
// "Super Knowledge" – Real‑life & general gaming facts (1500+ entries).
// All responses are phase‑aware (p = 0–5) and return strings.
// ─────────────────────────────────────────────────────────────────────────────

import { currentDay, ph, pick } from "./verity_core.js";

// ─────────────────────────────────────────────────────────────────────────────
// KNOWLEDGE DATABASE – keyed by lowercase, singular names.
// ─────────────────────────────────────────────────────────────────────────────

const KNOWLEDGE = {
  // ─── COUNTRIES ──────────────────────────────────────────────────────────
  "afghanistan": "A landlocked country in South Asia, capital Kabul.",
  "albania": "A country in Southeast Europe, capital Tirana.",
  "algeria": "A country in North Africa, capital Algiers.",
  "andorra": "A small principality in the Pyrenees, capital Andorra la Vella.",
  "angola": "A country in Southern Africa, capital Luanda.",
  "antigua and barbuda": "A twin‑island nation in the Caribbean, capital St. John's.",
  "argentina": "A large country in South America, capital Buenos Aires.",
  "armenia": "A country in the South Caucasus, capital Yerevan.",
  "australia": "A continent and country, capital Canberra.",
  "austria": "A country in Central Europe, capital Vienna.",
  "azerbaijan": "A country in the South Caucasus, capital Baku.",
  "bahamas": "An island nation in the Atlantic, capital Nassau.",
  "bahrain": "An island kingdom in the Persian Gulf, capital Manama.",
  "bangladesh": "A densely populated country in South Asia, capital Dhaka.",
  "barbados": "An island country in the Caribbean, capital Bridgetown.",
  "belarus": "A landlocked country in Eastern Europe, capital Minsk.",
  "belgium": "A country in Western Europe, capital Brussels.",
  "belize": "A country in Central America, capital Belmopan.",
  "benin": "A country in West Africa, capital Porto‑Novo.",
  "bhutan": "A Himalayan kingdom, capital Thimphu.",
  "bolivia": "A landlocked country in South America, capital Sucre (constitutional) and La Paz (administrative).",
  "bosnia and herzegovina": "A country in the Balkans, capital Sarajevo.",
  "botswana": "A country in Southern Africa, capital Gaborone.",
  "brazil": "The largest country in South America, capital Brasília.",
  "brunei": "A small sultanate on Borneo, capital Bandar Seri Begawan.",
  "bulgaria": "A country in Southeast Europe, capital Sofia.",
  "burkina faso": "A landlocked country in West Africa, capital Ouagadougou.",
  "burundi": "A country in East Africa, capital Gitega.",
  "cabo verde": "An island nation off West Africa, capital Praia.",
  "cambodia": "A country in Southeast Asia, capital Phnom Penh.",
  "cameroon": "A country in Central Africa, capital Yaoundé.",
  "canada": "A country in North America, capital Ottawa.",
  "central african republic": "A landlocked country in Central Africa, capital Bangui.",
  "chad": "A country in Central Africa, capital N'Djamena.",
  "chile": "A long country in South America, capital Santiago.",
  "china": "A vast country in East Asia, capital Beijing.",
  "colombia": "A country in South America, capital Bogotá.",
  "comoros": "An island country in the Indian Ocean, capital Moroni.",
  "congo (congo‑brazzaville)": "A country in Central Africa, capital Brazzaville.",
  "congo (congo‑kinshasa)": "A large country in Central Africa, capital Kinshasa.",
  "costa rica": "A country in Central America, capital San José.",
  "croatia": "A country in Southeast Europe, capital Zagreb.",
  "cuba": "An island nation in the Caribbean, capital Havana.",
  "cyprus": "An island country in the Eastern Mediterranean, capital Nicosia.",
  "czech republic": "A country in Central Europe, capital Prague.",
  "denmark": "A country in Northern Europe, capital Copenhagen.",
  "djibouti": "A country in the Horn of Africa, capital Djibouti.",
  "dominica": "An island nation in the Caribbean, capital Roseau.",
  "dominican republic": "A country in the Caribbean, capital Santo Domingo.",
  "east timor": "A country in Southeast Asia, capital Dili.",
  "ecuador": "A country in South America, capital Quito.",
  "egypt": "A country in North Africa, capital Cairo.",
  "el salvador": "A country in Central America, capital San Salvador.",
  "equatorial guinea": "A country in Central Africa, capital Malabo.",
  "eritrea": "A country in the Horn of Africa, capital Asmara.",
  "estonia": "A country in Northern Europe, capital Tallinn.",
  "eswatini": "A kingdom in Southern Africa, capitals Mbabane and Lobamba.",
  "ethiopia": "A country in the Horn of Africa, capital Addis Ababa.",
  "fiji": "An island nation in the Pacific, capital Suva.",
  "finland": "A country in Northern Europe, capital Helsinki.",
  "france": "A country in Western Europe, capital Paris.",
  "gabon": "A country in Central Africa, capital Libreville.",
  "gambia": "A small country in West Africa, capital Banjul.",
  "georgia": "A country in the Caucasus, capital Tbilisi.",
  "germany": "A country in Central Europe, capital Berlin.",
  "ghana": "A country in West Africa, capital Accra.",
  "greece": "A country in Southern Europe, capital Athens.",
  "grenada": "An island nation in the Caribbean, capital St. George's.",
  "guatemala": "A country in Central America, capital Guatemala City.",
  "guinea": "A country in West Africa, capital Conakry.",
  "guinea‑bissau": "A country in West Africa, capital Bissau.",
  "guyana": "A country in South America, capital Georgetown.",
  "haiti": "A country in the Caribbean, capital Port‑au‑Prince.",
  "honduras": "A country in Central America, capital Tegucigalpa.",
  "hungary": "A country in Central Europe, capital Budapest.",
  "iceland": "A Nordic island country, capital Reykjavík.",
  "india": "A large country in South Asia, capital New Delhi.",
  "indonesia": "A vast archipelago in Southeast Asia, capital Jakarta.",
  "iran": "A country in Western Asia, capital Tehran.",
  "iraq": "A country in Western Asia, capital Baghdad.",
  "ireland": "A country in Western Europe, capital Dublin.",
  "israel": "A country in the Middle East, capital Jerusalem (disputed).",
  "italy": "A country in Southern Europe, capital Rome.",
  "jamaica": "An island nation in the Caribbean, capital Kingston.",
  "japan": "An island country in East Asia, capital Tokyo.",
  "jordan": "A country in the Middle East, capital Amman.",
  "kazakhstan": "A large country in Central Asia, capital Astana.",
  "kenya": "A country in East Africa, capital Nairobi.",
  "kiribati": "An island nation in the Pacific, capital Tarawa.",
  "korea (north)": "A country in East Asia, capital Pyongyang.",
  "korea (south)": "A country in East Asia, capital Seoul.",
  "kuwait": "A country in the Middle East, capital Kuwait City.",
  "kyrgyzstan": "A country in Central Asia, capital Bishkek.",
  "laos": "A landlocked country in Southeast Asia, capital Vientiane.",
  "latvia": "A country in Northern Europe, capital Riga.",
  "lebanon": "A country in the Middle East, capital Beirut.",
  "lesotho": "A landlocked kingdom in Southern Africa, capital Maseru.",
  "liberia": "A country in West Africa, capital Monrovia.",
  "libya": "A country in North Africa, capital Tripoli.",
  "liechtenstein": "A small principality in Europe, capital Vaduz.",
  "lithuania": "A country in Northern Europe, capital Vilnius.",
  "luxembourg": "A small country in Western Europe, capital Luxembourg.",
  "madagascar": "An island country in the Indian Ocean, capital Antananarivo.",
  "malawi": "A landlocked country in Southeast Africa, capital Lilongwe.",
  "malaysia": "A country in Southeast Asia, capital Kuala Lumpur.",
  "maldives": "An island nation in the Indian Ocean, capital Malé.",
  "mali": "A landlocked country in West Africa, capital Bamako.",
  "malta": "An island country in the Mediterranean, capital Valletta.",
  "marshall islands": "An island nation in the Pacific, capital Majuro.",
  "mauritania": "A country in West Africa, capital Nouakchott.",
  "mauritius": "An island nation in the Indian Ocean, capital Port Louis.",
  "mexico": "A country in North America, capital Mexico City.",
  "micronesia": "A country in the Pacific, capital Palikir.",
  "moldova": "A country in Eastern Europe, capital Chișinău.",
  "monaco": "A small city‑state on the French Riviera, capital Monaco.",
  "mongolia": "A landlocked country in East Asia, capital Ulaanbaatar.",
  "montenegro": "A country in Southeast Europe, capital Podgorica.",
  "morocco": "A country in North Africa, capital Rabat.",
  "mozambique": "A country in Southeast Africa, capital Maputo.",
  "myanmar (burma)": "A country in Southeast Asia, capital Naypyidaw.",
  "namibia": "A country in Southern Africa, capital Windhoek.",
  "nauru": "A small island nation in the Pacific, no official capital.",
  "nepal": "A landlocked country in South Asia, capital Kathmandu.",
  "netherlands": "A country in Western Europe, capital Amsterdam (seat of government in The Hague).",
  "new zealand": "An island country in the Pacific, capital Wellington.",
  "nicaragua": "A country in Central America, capital Managua.",
  "niger": "A landlocked country in West Africa, capital Niamey.",
  "nigeria": "A country in West Africa, capital Abuja.",
  "norway": "A country in Northern Europe, capital Oslo.",
  "oman": "A country in the Middle East, capital Muscat.",
  "pakistan": "A country in South Asia, capital Islamabad.",
  "palau": "An island nation in the Pacific, capital Ngerulmud.",
  "panama": "A country in Central America, capital Panama City.",
  "papua new guinea": "A country in Oceania, capital Port Moresby.",
  "paraguay": "A landlocked country in South America, capital Asunción.",
  "peru": "A country in South America, capital Lima.",
  "philippines": "An archipelago in Southeast Asia, capital Manila.",
  "poland": "A country in Central Europe, capital Warsaw.",
  "portugal": "A country in Southern Europe, capital Lisbon.",
  "qatar": "A country in the Middle East, capital Doha.",
  "romania": "A country in Southeast Europe, capital Bucharest.",
  "russia": "The largest country in the world, capital Moscow.",
  "rwanda": "A country in East Africa, capital Kigali.",
  "saint kitts and nevis": "A twin‑island nation in the Caribbean, capital Basseterre.",
  "saint lucia": "An island nation in the Caribbean, capital Castries.",
  "saint vincent and the grenadines": "An island nation in the Caribbean, capital Kingstown.",
  "samoa": "A country in Oceania, capital Apia.",
  "san marino": "A small country in Europe, capital San Marino.",
  "sao tome and principe": "An island country in the Gulf of Guinea, capital São Tomé.",
  "saudi arabia": "A country in the Middle East, capital Riyadh.",
  "senegal": "A country in West Africa, capital Dakar.",
  "serbia": "A country in Southeast Europe, capital Belgrade.",
  "seychelles": "An island nation in the Indian Ocean, capital Victoria.",
  "sierra leone": "A country in West Africa, capital Freetown.",
  "singapore": "A city‑state in Southeast Asia, capital Singapore.",
  "slovakia": "A country in Central Europe, capital Bratislava.",
  "slovenia": "A country in Central Europe, capital Ljubljana.",
  "solomon islands": "A country in the Pacific, capital Honiara.",
  "somalia": "A country in the Horn of Africa, capital Mogadishu.",
  "south africa": "A country in Southern Africa, capitals Pretoria (administrative), Cape Town (legislative), Bloemfontein (judicial).",
  "south sudan": "A country in East Africa, capital Juba.",
  "spain": "A country in Southern Europe, capital Madrid.",
  "sri lanka": "An island country in South Asia, capital Sri Jayawardenepura Kotte (administrative) and Colombo (commercial).",
  "sudan": "A country in Northeast Africa, capital Khartoum.",
  "suriname": "A country in South America, capital Paramaribo.",
  "sweden": "A country in Northern Europe, capital Stockholm.",
  "switzerland": "A country in Central Europe, capital Bern.",
  "syria": "A country in the Middle East, capital Damascus.",
  "taiwan": "An island in East Asia, capital Taipei (disputed).",
  "tajikistan": "A country in Central Asia, capital Dushanbe.",
  "tanzania": "A country in East Africa, capital Dodoma.",
  "thailand": "A country in Southeast Asia, capital Bangkok.",
  "togo": "A country in West Africa, capital Lomé.",
  "tonga": "An island nation in the Pacific, capital Nukuʻalofa.",
  "trinidad and tobago": "A twin‑island nation in the Caribbean, capital Port of Spain.",
  "tunisia": "A country in North Africa, capital Tunis.",
  "turkey": "A transcontinental country, capital Ankara.",
  "turkmenistan": "A country in Central Asia, capital Ashgabat.",
  "tuvalu": "A small island nation in the Pacific, capital Funafuti.",
  "uganda": "A landlocked country in East Africa, capital Kampala.",
  "ukraine": "A country in Eastern Europe, capital Kyiv.",
  "united arab emirates": "A federation in the Middle East, capital Abu Dhabi.",
  "united kingdom": "A country in Western Europe, capital London.",
  "united states": "A country in North America, capital Washington, D.C.",
  "uruguay": "A country in South America, capital Montevideo.",
  "uzbekistan": "A country in Central Asia, capital Tashkent.",
  "vanuatu": "An island nation in the Pacific, capital Port Vila.",
  "vatican city": "A city‑state in Europe, capital Vatican City.",
  "venezuela": "A country in South America, capital Caracas.",
  "vietnam": "A country in Southeast Asia, capital Hanoi.",
  "yemen": "A country in the Middle East, capital Sana'a.",
  "zambia": "A landlocked country in Southern Africa, capital Lusaka.",
  "zimbabwe": "A landlocked country in Southern Africa, capital Harare.",

  // ─── CAPITALS (already covered above, but we'll add some extra) ────────
  // Not needed, but we can include a few extras.

  // ─── LANGUAGES ──────────────────────────────────────────────────────────
  "english": "A West Germanic language originally spoken in England, now the global lingua franca.",
  "spanish": "A Romance language spoken in Spain and the Americas.",
  "mandarin chinese": "The most spoken language in the world, part of the Sino‑Tibetan family.",
  "hindi": "An Indo‑Aryan language spoken in India.",
  "arabic": "A Semitic language spoken in the Arab world.",
  "bengali": "An Indo‑Aryan language spoken in Bangladesh and India.",
  "portuguese": "A Romance language spoken in Portugal, Brazil, and several African nations.",
  "russian": "An East Slavic language spoken in Russia and many former Soviet states.",
  "japanese": "A Japonic language spoken in Japan.",
  "western punjabi": "An Indo‑Aryan language spoken in Pakistan.",
  "marathi": "An Indo‑Aryan language spoken in India.",
  "telugu": "A Dravidian language spoken in India.",
  "turkish": "A Turkic language spoken in Turkey.",
  "tamil": "A Dravidian language spoken in India and Sri Lanka.",
  "urdu": "An Indo‑Aryan language spoken in Pakistan and India.",
  "korean": "A language isolate spoken in Korea.",
  "french": "A Romance language spoken in France and many African countries.",
  "german": "A West Germanic language spoken in Germany and Central Europe.",
  "vietnamese": "An Austroasiatic language spoken in Vietnam.",
  "italian": "A Romance language spoken in Italy.",
  "persian": "An Indo‑Iranian language spoken in Iran, Afghanistan, and Tajikistan.",
  "malay": "An Austronesian language spoken in Malaysia, Indonesia, and Brunei.",
  "thai": "A Kra‑Dai language spoken in Thailand.",
  "greek": "A Hellenic language spoken in Greece and Cyprus.",
  "dutch": "A West Germanic language spoken in the Netherlands and Belgium.",
  "polish": "A West Slavic language spoken in Poland.",
  "romanian": "A Romance language spoken in Romania and Moldova.",
  "czech": "A West Slavic language spoken in the Czech Republic.",
  "swedish": "A North Germanic language spoken in Sweden.",
  "hungarian": "A Uralic language spoken in Hungary.",
  "filipino": "An Austronesian language based on Tagalog, spoken in the Philippines.",
  "indonesian": "A standardized form of Malay, official in Indonesia.",
  "hebrew": "A Semitic language, revived as the official language of Israel.",
  "swahili": "A Bantu language spoken in East Africa.",
  "amharic": "A Semitic language spoken in Ethiopia.",
  "burmese": "A Sino‑Tibetan language spoken in Myanmar.",
  "khmer": "An Austroasiatic language spoken in Cambodia.",
  "lao": "A Kra‑Dai language spoken in Laos.",
  "sindhi": "An Indo‑Aryan language spoken in Pakistan.",
  "pashto": "An Eastern Iranian language spoken in Afghanistan and Pakistan.",
  "uzbek": "A Turkic language spoken in Uzbekistan.",
  "azerbaijani": "A Turkic language spoken in Azerbaijan.",
  "kazakh": "A Turkic language spoken in Kazakhstan.",
  "georgian": "A Kartvelian language spoken in Georgia.",
  "armenian": "An Indo‑European language spoken in Armenia.",
  "macedonian": "A South Slavic language spoken in North Macedonia.",
  "albanian": "An Indo‑European language spoken in Albania and Kosovo.",
  "mongolian": "A Mongolic language spoken in Mongolia.",
  "nepali": "An Indo‑Aryan language spoken in Nepal.",
  "sinhala": "An Indo‑Aryan language spoken in Sri Lanka.",
  "kyrgyz": "A Turkic language spoken in Kyrgyzstan.",
  "tajik": "A variety of Persian spoken in Tajikistan.",
  "turkmen": "A Turkic language spoken in Turkmenistan.",
  "danish": "A North Germanic language spoken in Denmark.",
  "norwegian": "A North Germanic language spoken in Norway.",
  "finnish": "A Uralic language spoken in Finland.",
  "estonian": "A Uralic language spoken in Estonia.",
  "latvian": "A Baltic language spoken in Latvia.",
  "lithuanian": "A Baltic language spoken in Lithuania.",
  "slovak": "A West Slavic language spoken in Slovakia.",
  "slovene": "A South Slavic language spoken in Slovenia.",
  "serbian": "A South Slavic language spoken in Serbia.",
  "croatian": "A South Slavic language spoken in Croatia.",
  "bosnian": "A South Slavic language spoken in Bosnia.",
  "montenegrin": "A South Slavic language spoken in Montenegro.",
  "bulgarian": "A South Slavic language spoken in Bulgaria.",
  "maltese": "A Semitic language with Romance influence, spoken in Malta.",
  "icelandic": "A North Germanic language spoken in Iceland.",
  "irish": "A Celtic language spoken in Ireland.",
  "welsh": "A Celtic language spoken in Wales.",
  "scottish gaelic": "A Celtic language spoken in Scotland.",
  "breton": "A Celtic language spoken in Brittany, France.",
  "basque": "A language isolate spoken in the Basque Country.",
  "occitan": "A Romance language spoken in southern France.",
  "catalan": "A Romance language spoken in Spain's Catalonia and other regions.",
  "galician": "A Romance language spoken in northwestern Spain.",
  "sardinian": "A Romance language spoken in Sardinia.",
  "friulian": "A Romance language spoken in northeastern Italy.",
  "ladin": "A Romance language spoken in the Dolomites.",
  "romansh": "A Romance language spoken in Switzerland.",
  "luxembourgish": "A West Germanic language spoken in Luxembourg.",
  "faroese": "A North Germanic language spoken in the Faroe Islands.",
  "greenlandic": "An Eskimo‑Aleut language spoken in Greenland.",
  "sami": "A group of Uralic languages spoken in Scandinavia.",
  "chechen": "A Northeast Caucasian language spoken in Chechnya.",
  "ingush": "A Northeast Caucasian language spoken in Ingushetia.",
  "avar": "A Northeast Caucasian language spoken in Dagestan.",
  "lezgi": "A Northeast Caucasian language spoken in Dagestan.",
  "ossetian": "An Eastern Iranian language spoken in the Caucasus.",
  "tatar": "A Turkic language spoken in Tatarstan.",
  "bashkir": "A Turkic language spoken in Bashkortostan.",
  "chuvash": "A Turkic language spoken in Chuvashia.",
  "kalmyk": "A Mongolic language spoken in Kalmykia.",
  "komi": "A Uralic language spoken in the Komi Republic.",
  "udmurt": "A Uralic language spoken in Udmurtia.",
  "mari": "A Uralic language spoken in Mari El.",
  "mordvin": "A Uralic language spoken in Mordovia.",
  "karelian": "A Uralic language spoken in Karelia.",
  "veps": "A Uralic language spoken in the Veps region.",
  "seto": "A Uralic language spoken in Estonia.",
  "võro": "A Uralic language spoken in Estonia.",
  "livonian": "A nearly extinct Uralic language.",
  "khanty": "A Uralic language spoken in Western Siberia.",
  "mansi": "A Uralic language spoken in Western Siberia.",
  "nenets": "A Uralic language spoken in the Russian Arctic.",
  "selkup": "A Uralic language spoken in Western Siberia.",
  "evenki": "A Tungusic language spoken in Siberia.",
  "even": "A Tungusic language spoken in Siberia.",
  "nanai": "A Tungusic language spoken in the Russian Far East.",
  "ulch": "A Tungusic language spoken in the Russian Far East.",
  "oroqen": "A Tungusic language spoken in China.",
  "manchu": "A nearly extinct Tungusic language.",
  "mongol": "A Mongolic language spoken in Mongolia.",
  "buriat": "A Mongolic language spoken in Buryatia.",
  "kalmyk": "A Mongolic language spoken in Kalmykia.",
  "dongxiang": "A Mongolic language spoken in China.",
  "tu": "A Mongolic language spoken in China.",
  "bonan": "A Mongolic language spoken in China.",
  "santa": "A Mongolic language spoken in China.",
  "yugur": "A Mongolic language spoken in China.",
  "japanese": "A Japonic language spoken in Japan.",
  "ryukyuan": "A group of Japonic languages spoken in the Ryukyu Islands.",
  "ainu": "A language isolate spoken in Hokkaido.",
  "korean": "A language isolate spoken in Korea.",
  "jeju": "A Koreanic language spoken on Jeju Island.",
  "vietnamese": "An Austroasiatic language spoken in Vietnam.",
  "khmer": "An Austroasiatic language spoken in Cambodia.",
  "mon": "An Austroasiatic language spoken in Myanmar.",
  "palaung": "An Austroasiatic language spoken in Myanmar and China.",
  "wa": "An Austroasiatic language spoken in Myanmar and China.",
  "bru": "An Austroasiatic language spoken in Laos.",
  "katu": "An Austroasiatic language spoken in Laos and Vietnam.",
  "jarai": "An Austronesian language spoken in Vietnam.",
  "rade": "An Austronesian language spoken in Vietnam.",
  "cham": "An Austronesian language spoken in Vietnam and Cambodia.",
  "malay": "An Austronesian language spoken in Malaysia, Indonesia, and Brunei.",
  "indonesian": "A standardized form of Malay.",
  "javanese": "An Austronesian language spoken in Java.",
  "sundanese": "An Austronesian language spoken in West Java.",
  "madurese": "An Austronesian language spoken in Madura.",
  "balinese": "An Austronesian language spoken in Bali.",
  "sasak": "An Austronesian language spoken in Lombok.",
  "sumbawa": "An Austronesian language spoken in Sumbawa.",
  "flores": "A group of Austronesian languages on Flores.",
  "timor": "A group of Austronesian languages in Timor.",
  "moluccan": "A group of Austronesian languages in the Moluccas.",
  "tagalog": "An Austronesian language spoken in the Philippines.",
  "cebuano": "An Austronesian language spoken in the Philippines.",
  "ilocano": "An Austronesian language spoken in the Philippines.",
  "hiligaynon": "An Austronesian language spoken in the Philippines.",
  "bicolano": "An Austronesian language spoken in the Philippines.",
  "waray": "An Austronesian language spoken in the Philippines.",
  "kapampangan": "An Austronesian language spoken in the Philippines.",
  "pangasinan": "An Austronesian language spoken in the Philippines.",
  "chavacano": "A Spanish‑based creole spoken in the Philippines.",
  "maori": "An Austronesian language spoken in New Zealand.",
  "hawaiian": "An Austronesian language spoken in Hawaii.",
  "samoan": "An Austronesian language spoken in Samoa.",
  "tongan": "An Austronesian language spoken in Tonga.",
  "fijian": "An Austronesian language spoken in Fiji.",
  "rotuman": "An Austronesian language spoken in Rotuma.",
  "tuvaluan": "An Austronesian language spoken in Tuvalu.",
  "gilbertese": "An Austronesian language spoken in Kiribati.",
  "nauruan": "An Austronesian language spoken in Nauru.",
  "marshallese": "An Austronesian language spoken in the Marshall Islands.",
  "palauan": "An Austronesian language spoken in Palau.",
  "chamorro": "An Austronesian language spoken in Guam.",
  "carolinian": "An Austronesian language spoken in the Northern Mariana Islands.",
  "woleaian": "An Austronesian language spoken in the Federated States of Micronesia.",
  "pingelapese": "An Austronesian language spoken in Pohnpei.",
  "pohnpeian": "An Austronesian language spoken in Pohnpei.",
  "kosraean": "An Austronesian language spoken in Kosrae.",
  "mortlockese": "An Austronesian language spoken in the Mortlock Islands.",
  "chukese": "An Austronesian language spoken in Chuuk.",
  "yapese": "An Austronesian language spoken in Yap.",
  "ulithian": "An Austronesian language spoken in Ulithi.",
  "woleai": "An Austronesian language spoken in Woleai.",
  "satawalese": "An Austronesian language spoken in Satawal.",
  "puluwatese": "An Austronesian language spoken in Puluwat.",
  "pulapese": "An Austronesian language spoken in Pulap.",
  "nukuoro": "An Austronesian language spoken in Nukuoro.",
  "kapingamarangi": "An Austronesian language spoken in Kapingamarangi.",
  "nukumanu": "An Austronesian language spoken in Nukumanu.",
  "ontong java": "An Austronesian language spoken in the Solomon Islands.",
  "sikaiana": "An Austronesian language spoken in Sikaiana.",
  "taumako": "An Austronesian language spoken in the Solomon Islands.",
  "anuta": "An Austronesian language spoken in Anuta.",
  "tikopia": "An Austronesian language spoken in Tikopia.",
  "raiwat": "An Austronesian language spoken in Vanuatu.",
  "ambae": "An Austronesian language spoken in Vanuatu.",
  "pentecost": "An Austronesian language spoken in Vanuatu.",
  "malekula": "An Austronesian language spoken in Vanuatu.",
  "epi": "An Austronesian language spoken in Vanuatu.",
  "efate": "An Austronesian language spoken in Vanuatu.",
  "tanna": "An Austronesian language spoken in Vanuatu.",
  "aneityum": "An Austronesian language spoken in Vanuatu.",
  "futuna": "An Austronesian language spoken in Futuna.",
  "alofi": "An Austronesian language spoken in Alofi.",
  "uvea": "An Austronesian language spoken in Uvea.",
  "wallisian": "An Austronesian language spoken in Wallis and Futuna.",
  "tikopian": "An Austronesian language spoken in Tikopia.",
  "sikaiana": "An Austronesian language spoken in Sikaiana.",
  "vatulele": "An Austronesian language spoken in Fiji.",
  "lakalai": "An Austronesian language spoken in Fiji.",
  "rotuman": "An Austronesian language spoken in Rotuma.",
  "norfolk": "A creole based on English, spoken on Norfolk Island.",
  "pitcairnese": "A creole based on English, spoken on Pitcairn Island.",
  "tok pisin": "A creole based on English, spoken in Papua New Guinea.",
  "pijin": "A creole based on English, spoken in the Solomon Islands.",
  "bislama": "A creole based on English, spoken in Vanuatu.",
  "hiri motu": "A creole based on Motu, spoken in Papua New Guinea.",
  "unserdeutsch": "A German‑based creole spoken in Papua New Guinea.",
  "krio": "A creole based on English, spoken in Sierra Leone.",
  "pichi": "A creole based on English, spoken in Equatorial Guinea.",
  "nigerian pidgin": "A creole based on English, spoken in Nigeria.",
  "cameroonian pidgin": "A creole based on English, spoken in Cameroon.",
  "ghanaian pidgin": "A creole based on English, spoken in Ghana.",
  "jamaican patois": "A creole based on English, spoken in Jamaica.",
  "bahamian": "A creole based on English, spoken in the Bahamas.",
  "tobagonian": "A creole based on English, spoken in Tobago.",
  "trinidadian": "A creole based on English, spoken in Trinidad.",
  "guyanese": "A creole based on English, spoken in Guyana.",
  "sranan": "A creole based on English, spoken in Suriname.",
  "saramaccan": "A creole based on English and Portuguese, spoken in Suriname.",
  "ndjuka": "A creole based on English, spoken in Suriname.",
  "papiamento": "A creole based on Spanish and Portuguese, spoken in Aruba, Curaçao, and Bonaire.",
  "cabo verdean creole": "A creole based on Portuguese, spoken in Cabo Verde.",
  "guinea‑bissau creole": "A creole based on Portuguese, spoken in Guinea‑Bissau.",
  "são tomense": "A creole based on Portuguese, spoken in São Tomé and Príncipe.",
  "principense": "A creole based on Portuguese, spoken in Príncipe.",
  "angolar": "A creole based on Portuguese, spoken in São Tomé.",
  "annobonese": "A creole based on Portuguese, spoken in Annobón.",
  "chabacano": "A Spanish‑based creole spoken in the Philippines.",
  "palenquero": "A Spanish‑based creole spoken in Colombia.",
  "papiamento": "A Spanish‑based creole spoken in the Caribbean.",
  "lunfardo": "A Spanish‑based slang from Argentina.",
  "spanglish": "A mixture of Spanish and English.",
  "franglais": "A mixture of French and English.",
  "denglisch": "A mixture of German and English.",
  "portuñol": "A mixture of Portuguese and Spanish.",
  "hindustani": "A mix of Hindi and Urdu.",
  "anglais": "A mix of English and French in Quebec.",
  "singlish": "A mix of English and Chinese in Singapore.",
  "manglish": "A mix of English and Malay in Malaysia.",
  "taglish": "A mix of Tagalog and English in the Philippines.",
  "korean english": "A mix of Korean and English.",
  "japlish": "A mix of Japanese and English.",
  "konglish": "A mix of Korean and English.",
  "chinese english": "A mix of Chinese and English.",
  "indian english": "A variety of English influenced by Indian languages.",
  "australian english": "A variety of English with distinctive vocabulary.",
  "new zealand english": "A variety of English with Māori influences.",
  "south african english": "A variety of English with Afrikaans and indigenous influences.",
  "canadian english": "A variety of English with American and British influences.",
  "american english": "A variety of English with many regional dialects.",
  "british english": "The original English with many regional dialects.",
  "scottish english": "A variety of English with Scots influences.",
  "welsh english": "A variety of English with Welsh influences.",
  "irish english": "A variety of English with Irish influences.",
  "caribbean english": "A variety of English with African and indigenous influences.",
  "african american vernacular english": "A variety of English with its own grammar and vocabulary.",
  "cockney": "A dialect of English from East London.",
  "geordie": "A dialect from Newcastle, England.",
  "scouse": "A dialect from Liverpool, England.",
  "brummie": "A dialect from Birmingham, England.",
  "west country": "A dialect from the West Country, England.",
  "yorkshire": "A dialect from Yorkshire, England.",
  "northern english": "A group of dialects from Northern England.",
  "midlands": "A dialect from the Midlands, England.",
  "estuary english": "A dialect from around the Thames Estuary.",
  "received pronunciation": "The standard accent of British English.",
  "general american": "The standard accent of American English.",
  "midwestern": "A dialect from the US Midwest.",
  "southern american": "A dialect from the Southern US.",
  "new york": "A dialect from New York City.",
  "boston": "A dialect from Boston, US.",
  "chicago": "A dialect from Chicago, US.",
  "texan": "A dialect from Texas, US.",
  "californian": "A dialect from California, US.",
  "appalachian": "A dialect from Appalachia, US.",
  "hiberno-english": "A dialect of English from Ireland.",
  "anglo-indian": "A dialect from India with English vocabulary.",
  "south asian english": "A dialect of English from South Asia.",
  "african english": "A dialect of English from Africa.",
  "caribbean english": "A dialect from the Caribbean.",
  "pacific english": "A dialect from the Pacific islands.",

  // ─── SCIENTIFIC ELEMENTS ──────────────────────────────────────────────
  "hydrogen": "The first element, atomic number 1, symbol H. It is the most abundant element in the universe.",
  "helium": "The second element, atomic number 2, symbol He. A noble gas, used in balloons.",
  "lithium": "Atomic number 3, symbol Li. A light metal used in batteries.",
  "beryllium": "Atomic number 4, symbol Be. A lightweight metal used in aerospace.",
  "boron": "Atomic number 5, symbol B. A metalloid used in glass and detergents.",
  "carbon": "Atomic number 6, symbol C. The basis of all known life. Found in diamonds and graphite.",
  "nitrogen": "Atomic number 7, symbol N. Makes up 78% of Earth's atmosphere.",
  "oxygen": "Atomic number 8, symbol O. Essential for respiration and combustion.",
  "fluorine": "Atomic number 9, symbol F. The most electronegative element, used in toothpaste.",
  "neon": "Atomic number 10, symbol Ne. A noble gas used in neon signs.",
  "sodium": "Atomic number 11, symbol Na. A reactive metal used in salt.",
  "magnesium": "Atomic number 12, symbol Mg. A light metal used in alloys.",
  "aluminium": "Atomic number 13, symbol Al. A lightweight metal used in packaging and construction.",
  "silicon": "Atomic number 14, symbol Si. A semiconductor, the basis of modern electronics.",
  "phosphorus": "Atomic number 15, symbol P. Essential for life, used in fertilizers.",
  "sulfur": "Atomic number 16, symbol S. Used in gunpowder and rubber.",
  "chlorine": "Atomic number 17, symbol Cl. Used in disinfectants and PVC.",
  "argon": "Atomic number 18, symbol Ar. A noble gas used in lighting.",
  "potassium": "Atomic number 19, symbol K. Essential for life, used in fertilizers.",
  "calcium": "Atomic number 20, symbol Ca. Essential for bones and teeth.",
  "scandium": "Atomic number 21, symbol Sc. Used in aerospace alloys.",
  "titanium": "Atomic number 22, symbol Ti. Strong, lightweight metal used in implants and aerospace.",
  "vanadium": "Atomic number 23, symbol V. Used in steel alloys.",
  "chromium": "Atomic number 24, symbol Cr. Used in stainless steel.",
  "manganese": "Atomic number 25, symbol Mn. Used in steel production.",
  "iron": "Atomic number 26, symbol Fe. The most common element in Earth's core, used in steel.",
  "cobalt": "Atomic number 27, symbol Co. Used in magnets and batteries.",
  "nickel": "Atomic number 28, symbol Ni. Used in alloys and coins.",
  "copper": "Atomic number 29, symbol Cu. Used in wiring and plumbing.",
  "zinc": "Atomic number 30, symbol Zn. Used in galvanization and alloys.",
  "gallium": "Atomic number 31, symbol Ga. Melts in your hand, used in semiconductors.",
  "germanium": "Atomic number 32, symbol Ge. A semiconductor.",
  "arsenic": "Atomic number 33, symbol As. A toxic metalloid, used in pesticides.",
  "selenium": "Atomic number 34, symbol Se. Used in photocopiers and glass.",
  "bromine": "Atomic number 35, symbol Br. A red-brown liquid used in flame retardants.",
  "krypton": "Atomic number 36, symbol Kr. A noble gas used in lasers.",
  "rubidium": "Atomic number 37, symbol Rb. A reactive metal used in atomic clocks.",
  "strontium": "Atomic number 38, symbol Sr. Used in fireworks and magnets.",
  "yttrium": "Atomic number 39, symbol Y. Used in lasers and superconductors.",
  "zirconium": "Atomic number 40, symbol Zr. Used in nuclear reactors.",
  "niobium": "Atomic number 41, symbol Nb. Used in superconducting magnets.",
  "molybdenum": "Atomic number 42, symbol Mo. Used in steel alloys.",
  "technetium": "Atomic number 43, symbol Tc. A radioactive element, used in medicine.",
  "ruthenium": "Atomic number 44, symbol Ru. A platinum group metal.",
  "rhodium": "Atomic number 45, symbol Rh. Used in catalytic converters.",
  "palladium": "Atomic number 46, symbol Pd. Used in catalysis and jewelry.",
  "silver": "Atomic number 47, symbol Ag. Used in jewelry, electronics, and mirrors.",
  "cadmium": "Atomic number 48, symbol Cd. Used in batteries and pigments.",
  "indium": "Atomic number 49, symbol In. Used in touchscreens and solders.",
  "tin": "Atomic number 50, symbol Sn. Used in solders and alloys.",
  "antimony": "Atomic number 51, symbol Sb. Used in flame retardants.",
  "tellurium": "Atomic number 52, symbol Te. Used in alloys and solar cells.",
  "iodine": "Atomic number 53, symbol I. Essential for thyroid health.",
  "xenon": "Atomic number 54, symbol Xe. A noble gas used in lighting.",
  "caesium": "Atomic number 55, symbol Cs. Used in atomic clocks.",
  "barium": "Atomic number 56, symbol Ba. Used in medical imaging.",
  "lanthanum": "Atomic number 57, symbol La. Used in optical glass.",
  "cerium": "Atomic number 58, symbol Ce. Used in catalytic converters.",
  "praseodymium": "Atomic number 59, symbol Pr. Used in magnets and lasers.",
  "neodymium": "Atomic number 60, symbol Nd. Used in strong magnets.",
  "promethium": "Atomic number 61, symbol Pm. A radioactive element.",
  "samarium": "Atomic number 62, symbol Sm. Used in magnets and lasers.",
  "europium": "Atomic number 63, symbol Eu. Used in phosphors for screens.",
  "gadolinium": "Atomic number 64, symbol Gd. Used in MRI contrast agents.",
  "terbium": "Atomic number 65, symbol Tb. Used in green phosphors.",
  "dysprosium": "Atomic number 66, symbol Dy. Used in magnets and lasers.",
  "holmium": "Atomic number 67, symbol Ho. Used in lasers.",
  "erbium": "Atomic number 68, symbol Er. Used in fiber optics.",
  "thulium": "Atomic number 69, symbol Tm. Used in portable X‑ray machines.",
  "ytterbium": "Atomic number 70, symbol Yb. Used in lasers.",
  "lutetium": "Atomic number 71, symbol Lu. Used in semiconductors.",
  "hafnium": "Atomic number 72, symbol Hf. Used in nuclear reactors.",
  "tantalum": "Atomic number 73, symbol Ta. Used in electronics and implants.",
  "tungsten": "Atomic number 74, symbol W. Used in light bulbs and tools.",
  "rhenium": "Atomic number 75, symbol Re. Used in superalloys.",
  "osmium": "Atomic number 76, symbol Os. The densest naturally occurring element.",
  "iridium": "Atomic number 77, symbol Ir. Used in spark plugs and pens.",
  "platinum": "Atomic number 78, symbol Pt. Used in jewelry and catalytic converters.",
  "gold": "Atomic number 79, symbol Au. Used in jewelry, electronics, and currency.",
  "mercury": "Atomic number 80, symbol Hg. A liquid metal used in thermometers.",
  "thallium": "Atomic number 81, symbol Tl. A toxic element used in electronics.",
  "lead": "Atomic number 82, symbol Pb. Used in batteries and radiation shielding.",
  "bismuth": "Atomic number 83, symbol Bi. A nontoxic metal used in cosmetics.",
  "polonium": "Atomic number 84, symbol Po. A radioactive element.",
  "astatine": "Atomic number 85, symbol At. A rare radioactive halogen.",
  "radon": "Atomic number 86, symbol Rn. A radioactive noble gas.",
  "francium": "Atomic number 87, symbol Fr. A radioactive alkali metal.",
  "radium": "Atomic number 88, symbol Ra. Used in radiotherapy.",
  "actinium": "Atomic number 89, symbol Ac. A radioactive element.",
  "thorium": "Atomic number 90, symbol Th. Used in nuclear reactors.",
  "protactinium": "Atomic number 91, symbol Pa. A radioactive element.",
  "uranium": "Atomic number 92, symbol U. Used in nuclear power and weapons.",
  "neptunium": "Atomic number 93, symbol Np. A radioactive element.",
  "plutonium": "Atomic number 94, symbol Pu. Used in nuclear weapons and reactors.",
  "americium": "Atomic number 95, symbol Am. Used in smoke detectors.",
  "curium": "Atomic number 96, symbol Cm. A radioactive element.",
  "berkelium": "Atomic number 97, symbol Bk. A radioactive element.",
  "californium": "Atomic number 98, symbol Cf. Used in neutron sources.",
  "einsteinium": "Atomic number 99, symbol Es. A radioactive element.",
  "fermium": "Atomic number 100, symbol Fm. A radioactive element.",
  "mendelevium": "Atomic number 101, symbol Md. A radioactive element.",
  "nobelium": "Atomic number 102, symbol No. A radioactive element.",
  "lawrencium": "Atomic number 103, symbol Lr. A radioactive element.",
  "rutherfordium": "Atomic number 104, symbol Rf. A synthetic element.",
  "dubnium": "Atomic number 105, symbol Db. A synthetic element.",
  "seaborgium": "Atomic number 106, symbol Sg. A synthetic element.",
  "bohrium": "Atomic number 107, symbol Bh. A synthetic element.",
  "hassium": "Atomic number 108, symbol Hs. A synthetic element.",
  "meitnerium": "Atomic number 109, symbol Mt. A synthetic element.",
  "darmstadtium": "Atomic number 110, symbol Ds. A synthetic element.",
  "roentgenium": "Atomic number 111, symbol Rg. A synthetic element.",
  "copernicium": "Atomic number 112, symbol Cn. A synthetic element.",
  "nihonium": "Atomic number 113, symbol Nh. A synthetic element.",
  "flerovium": "Atomic number 114, symbol Fl. A synthetic element.",
  "moscovium": "Atomic number 115, symbol Mc. A synthetic element.",
  "livermorium": "Atomic number 116, symbol Lv. A synthetic element.",
  "tennessine": "Atomic number 117, symbol Ts. A synthetic element.",
  "oganesson": "Atomic number 118, symbol Og. A synthetic element.",

  // ─── PLANETS ────────────────────────────────────────────────────────────
  "mercury": "The smallest and closest planet to the Sun. It has no atmosphere and extreme temperatures.",
  "venus": "The second planet from the Sun, the hottest due to a thick CO₂ atmosphere. Similar in size to Earth.",
  "earth": "The third planet, home to all known life. It has liquid water and a nitrogen‑oxygen atmosphere.",
  "mars": "The fourth planet, known as the Red Planet due to iron oxide. Has the largest volcano, Olympus Mons.",
  "jupiter": "The largest planet in the Solar System, a gas giant with a Great Red Spot.",
  "saturn": "The sixth planet, known for its prominent ring system made of ice and rock.",
  "uranus": "The seventh planet, an ice giant with a tilted rotation axis.",
  "neptune": "The eighth and farthest planet, a blue ice giant with strong winds.",
  "pluto": "A dwarf planet in the Kuiper Belt, formerly considered the ninth planet.",

  // ─── MAJOR HISTORICAL EVENTS ─────────────────────────────────────────
  "world war i": "A global conflict from 1914 to 1918, involving the Allied Powers and Central Powers.",
  "world war ii": "A global conflict from 1939 to 1945, involving the Allies and Axis powers.",
  "american revolution": "The 1775‑1783 conflict in which the American colonies gained independence from Britain.",
  "french revolution": "The 1789‑1799 period of radical social and political upheaval in France.",
  "russian revolution": "The 1917 revolution that overthrew the monarchy and established the Soviet Union.",
  "cold war": "The geopolitical tension between the US and the Soviet Union from 1947 to 1991.",
  "fall of the berlin wall": "In 1989, the wall separating East and West Berlin fell, symbolizing the end of the Cold War.",
  "moon landing": "In 1969, the Apollo 11 mission landed the first humans on the Moon.",
  "invention of the internet": "The Internet evolved from ARPANET in the 1960s and became widespread in the 1990s.",
  "industrial revolution": "A period of rapid industrialisation from the late 18th to early 19th century.",
  "renaissance": "A period of cultural and artistic revival in Europe from the 14th to 17th centuries.",
  "enlightenment": "An intellectual movement in the 17th‑18th centuries emphasizing reason and individualism.",
  "age of exploration": "The period from the 15th to 17th centuries when Europeans explored and colonised the world.",
  "scientific revolution": "A period of rapid scientific discovery in the 16th‑17th centuries.",
  "printing press": "Invented by Johannes Gutenberg around 1440, revolutionised the spread of knowledge.",
  "steam engine": "Developed in the 18th century, powered the Industrial Revolution.",
  "electricity": "The discovery and harnessing of electricity transformed the modern world.",
  "theory of relativity": "Albert Einstein's 1905 theory revolutionised physics.",
  "germ theory": "Proved that microorganisms cause disease, revolutionising medicine.",
  "darwin's evolution": "Charles Darwin's theory of evolution by natural selection (1859) changed biology.",

  // ─── POPULAR GAMES (NON‑MINECRAFT) ──────────────────────────────────
  "the legend of zelda": "A popular action‑adventure franchise by Nintendo, first released in 1986.",
  "super mario": "A platformer franchise by Nintendo, featuring Mario and Luigi.",
  "pokémon": "A media franchise by Nintendo, Game Freak, and Creatures, focusing on creature collection.",
  "call of duty": "A popular first‑person shooter franchise by Activision.",
  "fortnite": "A battle royale game by Epic Games, known for its building mechanics.",
  "grand theft auto": "An open‑world action‑adventure franchise by Rockstar Games.",
  "minecraft": "A sandbox game by Mojang, known for building and exploration.",
  "world of warcraft": "A massively multiplayer online role‑playing game by Blizzard.",
  "league of legends": "A multiplayer online battle arena game by Riot Games.",
  "dota 2": "A multiplayer online battle arena game by Valve.",
  "counter‑strike": "A tactical first‑person shooter by Valve.",
  "valorant": "A tactical first‑person shooter by Riot Games.",
  "overwatch": "A team‑based first‑person shooter by Blizzard.",
  "apex legends": "A battle royale game by Respawn Entertainment.",
  "pubg": "PlayerUnknown's Battlegrounds, a battle royale game.",
  "roblox": "An online platform for user‑created games and experiences.",
  "terraria": "A 2D sandbox game with exploration and combat.",
  "stardew valley": "A farming simulation RPG by ConcernedApe.",
  "animal crossing": "A social simulation game series by Nintendo.",
  "among us": "A multiplayer social deduction game by InnerSloth.",
  "fall guys": "A multiplayer obstacle course game by Mediatonic.",
  "rocket league": "A vehicular soccer game by Psyonix.",
  "the witcher 3": "An open‑world RPG by CD Projekt Red.",
  "cyberpunk 2077": "A futuristic open‑world RPG by CD Projekt Red.",
  "red dead redemption 2": "A Western open‑world game by Rockstar Games.",
  "god of war": "An action‑adventure game by Sony Santa Monica.",
  "the last of us": "A post‑apocalyptic action‑adventure by Naughty Dog.",
  "uncharted": "An action‑adventure series by Naughty Dog.",
  "horizon zero dawn": "An open‑world action‑RPG by Guerrilla Games.",
  "bloodborne": "An action‑RPG by FromSoftware.",
  "dark souls": "A challenging action‑RPG series by FromSoftware.",
  "elden ring": "An open‑world action‑RPG by FromSoftware.",
  "sekiro": "An action‑adventure game by FromSoftware.",
  "final fantasy": "A long‑running RPG franchise by Square Enix.",
  "kingdom hearts": "An action‑RPG crossover series by Square Enix and Disney.",
  "resident evil": "A survival horror franchise by Capcom.",
  "silent hill": "A survival horror franchise by Konami.",
  "metal gear solid": "A stealth action franchise by Konami.",
  "street fighter": "A fighting game franchise by Capcom.",
  "mortal kombat": "A fighting game franchise by NetherRealm Studios.",
  "tekken": "A fighting game franchise by Bandai Namco.",
  "smash bros": "A crossover fighting game by Nintendo.",
  "splatoon": "A third‑person shooter franchise by Nintendo.",
  "kirby": "A platformer franchise by Nintendo.",
  "sonic": "A platformer franchise by Sega.",
  "crash bandicoot": "A platformer franchise by Activision.",
  "spyro": "A platformer franchise by Activision.",
  "ratchet & clank": "A platformer franchise by Insomniac Games.",
  "jak and daxter": "An action‑platformer franchise by Naughty Dog.",
  "sly cooper": "A platformer franchise by Sucker Punch.",
  "inFamous": "An action‑adventure franchise by Sucker Punch.",
  "prototype": "An action‑adventure franchise by Radical Entertainment.",
  "infamous": "An open‑world superhero game by Sucker Punch.",
  "spider‑man": "A superhero action game by Insomniac Games.",
  "batman: arkham": "A superhero action series by Rocksteady.",
  "marvel's avengers": "A superhero action game by Crystal Dynamics.",
  "guardians of the galaxy": "A superhero action game by Eidos‑Montréal.",
  "x‑com": "A turn‑based strategy franchise by Firaxis.",
  "civilization": "A turn‑based strategy franchise by Sid Meier.",
  "europa universalis": "A grand strategy game by Paradox Interactive.",
  "crusader kings": "A grand strategy game by Paradox Interactive.",
  "hearts of iron": "A grand strategy game by Paradox Interactive.",
  "stellaris": "A grand strategy game by Paradox Interactive.",
  "total war": "A turn‑based strategy franchise by Creative Assembly.",
  "age of empires": "A real‑time strategy franchise by Ensemble Studios.",
  "starCraft": "A real‑time strategy franchise by Blizzard.",
  "warcraft": "A real‑time strategy franchise by Blizzard.",
  "command & conquer": "A real‑time strategy franchise by Westwood Studios.",
  "red alert": "A sub‑series of Command & Conquer.",
  "dune": "A real‑time strategy game based on the novel.",
  "homeworld": "A real‑time strategy game in space.",
  "sins of a solar empire": "A real‑time strategy game in space.",
  "galactic civilizations": "A turn‑based strategy game in space.",
  "master of orion": "A turn‑based strategy game in space.",
  "endless space": "A turn‑based strategy game in space.",
  "stellaris": "A grand strategy game in space.",
  "halo": "A first‑person shooter franchise by Bungie.",
  "destiny": "A first‑person shooter franchise by Bungie.",
  "titanfall": "A first‑person shooter franchise by Respawn.",
  "battlefield": "A first‑person shooter franchise by EA DICE.",
  "battlefront": "A first‑person shooter based on Star Wars.",
  "bioshock": "A first‑person shooter with RPG elements by Irrational Games.",
  "borderlands": "A first‑person shooter with RPG elements by Gearbox.",
  "dishonored": "A stealth action game by Arkane Studios.",
  "prey": "A first‑person shooter by Arkane Studios.",
  "doom": "A first‑person shooter franchise by id Software.",
  "quake": "A first‑person shooter franchise by id Software.",
  "wolfenstein": "A first‑person shooter franchise by id Software.",
  "far cry": "A first‑person shooter franchise by Ubisoft.",
  "crysis": "A first‑person shooter franchise by Crytek.",
  "metro": "A first‑person shooter franchise by 4A Games.",
  "stalker": "A first‑person shooter franchise by GSC Game World.",
  "team fortress 2": "A team‑based first‑person shooter by Valve.",
  "overwatch": "A team‑based first‑person shooter by Blizzard.",
  "paladins": "A team‑based first‑person shooter by Hi‑Rez.",
  "rainbow six siege": "A tactical first‑person shooter by Ubisoft.",
  "csgo": "Counter‑Strike: Global Offensive, a tactical shooter by Valve.",
  "valorant": "A tactical shooter by Riot Games.",
  "call of duty: modern warfare": "A popular sub‑series of Call of Duty.",
  "call of duty: black ops": "A sub‑series of Call of Duty.",
  "battlefield 1": "A Battlefield game set in World War I.",
  "battlefield v": "A Battlefield game set in World War II.",
  "battlefield 2042": "A Battlefield game set in the future.",
  "fortnite": "A battle royale game with building.",
  "pubg": "A battle royale game.",
  "apex legends": "A battle royale game with heroes.",
  "warzone": "Call of Duty's battle royale mode.",
  "firestorm": "Battlefield's battle royale mode.",
  "fall guys": "A multiplayer obstacle course game.",
  "among us": "A social deduction game.",
  "rocket league": "A vehicular soccer game.",
  "roblox": "A platform for user‑created games.",
  "rec room": "A social VR game.",
  "vr chat": "A social VR game.",
  "beat saber": "A VR rhythm game.",
  "superhot": "A first‑person shooter where time moves when you move.",
  "half‑life": "A first‑person shooter franchise by Valve.",
  "portal": "A puzzle game franchise by Valve.",
  "left 4 dead": "A cooperative zombie shooter by Valve.",
  "team fortress": "A team‑based shooter by Valve.",
  "death stranding": "An open‑world game by Hideo Kojima.",
  "metal gear solid": "A stealth action franchise by Hideo Kojima.",
  "the phantom pain": "A sub‑series of Metal Gear Solid.",
  "horizon zero dawn": "An open‑world RPG with robot dinosaurs.",
  "forbidden west": "The sequel to Horizon Zero Dawn.",
  "god of war ragnarok": "The sequel to God of War (2018).",
  "the last of us part ii": "The sequel to The Last of Us.",
  "ghost of tsushima": "An open‑world game set in feudal Japan.",
  "days gone": "An open‑world zombie game.",
  "death stranding": "A game about reconnecting a fractured America.",
  "control": "A supernatural action game by Remedy.",
  "alan wake": "A psychological thriller by Remedy.",
  "quantum break": "A science fiction game by Remedy.",
  "max payne": "A noir action game by Remedy.",
  "hitman": "A stealth assassination franchise by IO Interactive.",
  "tomb raider": "An action‑adventure franchise by Crystal Dynamics.",
  "rise of the tomb raider": "The sequel to Tomb Raider.",
  "shadow of the tomb raider": "The third game in the reboot series.",
  "uncharted 4": "The final game in the Uncharted series.",
  "the lost legacy": "A spin‑off of Uncharted.",
  "the last of us": "A post‑apocalyptic game.",
  "days gone": "A post‑apocalyptic game with zombies.",
  "mad max": "An open‑world game based on the film.",
  "the witcher 3": "A fantasy RPG based on the books.",
  "cyberpunk 2077": "A futuristic RPG.",
  "red dead redemption": "A Western open‑world game.",
  "red dead redemption 2": "The prequel to RDR.",
  "grand theft auto v": "The latest mainline GTA game.",
  "gta online": "The multiplayer component of GTA V.",
  "mafia": "An open‑world crime game.",
  "yakuza": "A crime drama series from Japan.",
  "judgment": "A spin‑off of Yakuza.",
  "shenmue": "An open‑world game from Sega.",
  "persona": "An RPG series by Atlus.",
  "shin megami tensei": "An RPG series by Atlus.",
  "dragon quest": "A long‑running RPG series by Square Enix.",
  "nioh": "A challenging action‑RPG by Team Ninja.",
  "nioh 2": "The sequel to Nioh.",
  "ghost of tsushima": "An open‑world game in Japan.",
  "sekiro": "A game about a shinobi.",
  "elden ring": "An open‑world game by FromSoftware.",
  "dark souls": "A challenging action‑RPG series.",
  "bloodborne": "A Victorian‑themed action‑RPG.",
  "demon's souls": "The predecessor to Dark Souls.",
  "armored core": "A mecha action series by FromSoftware.",
  "king's field": "An early RPG by FromSoftware.",
  "kenshi": "An open‑world sandbox RPG.",
  "mount & blade": "A sandbox RPG with tactical combat.",
  "bannerlord": "The sequel to Mount & Blade.",
  "kingdom come deliverance": "A realistic RPG set in medieval Bohemia.",
  "disco elysium": "A unique RPG with no combat, focused on dialogue.",
  "planescape torment": "A classic RPG with deep narrative.",
  "baldur's gate": "A classic RPG series by BioWare.",
  "icewind dale": "A classic RPG by BioWare.",
  "pillars of eternity": "A modern RPG in the style of Baldur's Gate.",
  "pathfinder: kingmaker": "An RPG based on the Pathfinder system.",
  "pathfinder: wrath of the righteous": "The sequel to Kingmaker.",
  "divinity: original sin": "A modern RPG with turn‑based combat.",
  "divinity: original sin 2": "The sequel to DOS.",
  "torment: tides of numenera": "A spiritual successor to Planescape.",
  "wasteland": "A post‑apocalyptic RPG series.",
  "fallout": "A post‑apocalyptic RPG series by Bethesda.",
  "fallout 3": "The first 3D Fallout.",
  "fallout: new vegas": "A fan‑favourite Fallout game.",
  "fallout 4": "The latest single‑player Fallout.",
  "fallout 76": "The online multiplayer Fallout.",
  "the elder scrolls": "A fantasy RPG series by Bethesda.",
  "oblivion": "The fourth Elder Scrolls game.",
  "skyrim": "The fifth Elder Scrolls game.",
  "morrowind": "The third Elder Scrolls game.",
  "daggerfall": "The second Elder Scrolls game.",
  "arena": "The first Elder Scrolls game.",
  "starfield": "Bethesda's space RPG.",
  "the outer worlds": "A space RPG by Obsidian Entertainment.",
  "outer wilds": "A space exploration game.",
  "no man's sky": "A space exploration game by Hello Games.",
  "elite dangerous": "A space simulation game.",
  "star citizen": "A space simulation game in development.",
  "mass effect": "A space opera RPG series by BioWare.",
  "mass effect 2": "The second Mass Effect game.",
  "mass effect 3": "The third Mass Effect game.",
  "mass effect: andromeda": "A spin‑off Mass Effect.",
  "dragon age": "A fantasy RPG series by BioWare.",
  "origins": "The first Dragon Age game.",
  "dragon age ii": "The second Dragon Age game.",
  "inquisition": "The third Dragon Age game.",
  "dreadwolf": "The upcoming fourth Dragon Age game.",
  "jade empire": "A martial arts RPG by BioWare.",
  "star wars: knights of the old republic": "A Star Wars RPG by BioWare.",
  "knights of the old republic ii": "The sequel by Obsidian.",
  "the old republic": "A Star Wars MMO.",
  "world of warcraft": "The most popular MMO.",
  "final fantasy xiv": "A popular MMORPG by Square Enix.",
  "the elder scrolls online": "The MMO version of TES.",
  "guild wars 2": "A popular MMO by ArenaNet.",
  "black desert online": "An action MMO by Pearl Abyss.",
  "lost ark": "An isometric MMO by Smilegate.",
  "new world": "An MMO by Amazon Games.",
  "destiny 2": "A sci‑fi MMO shooter by Bungie.",
  "warframe": "A free‑to‑play sci‑fi shooter.",
  "path of exile": "A free‑to‑play action RPG.",
  "diablo": "A hack‑and‑slash RPG series by Blizzard.",
  "diablo ii": "A classic action RPG.",
  "diablo iii": "The third Diablo game.",
  "diablo iv": "The upcoming fourth Diablo game.",
  "torchlight": "An action RPG series by Runic Games.",
  "torchlight ii": "The sequel to Torchlight.",
  "torchlight iii": "The third Torchlight game.",
  "grim dawn": "An action RPG by Crate Entertainment.",
  "titan quest": "A classic action RPG set in mythology.",
  "sacred": "An action RPG series.",
  "sacred 2": "The sequel to Sacred.",
  "divinity: original sin": "A turn‑based RPG.",
  "divinity: original sin 2": "The sequel.",
  "dragon's dogma": "An action RPG by Capcom.",
  "dragon's dogma ii": "The upcoming sequel.",
  "kingdoms of amalur": "An RPG by 38 Studios.",
  "re‑reckoning": "The remaster of Kingdoms of Amalur.",
  "fable": "An RPG series by Lionhead Studios.",
  "fable ii": "The second Fable game.",
  "fable iii": "The third Fable game.",
  "fable: the lost chapters": "The expanded version of Fable.",
  "black & white": "A god game by Lionhead.",
  "populous": "A classic god game.",
  "sim city": "A city‑building game by Maxis.",
  "the sims": "A life simulation game by Maxis.",
  "spore": "A evolutionary game by Maxis.",
  "roller coaster tycoon": "A theme park simulation game.",
  "planet coaster": "A modern theme park sim.",
  "planet zoo": "A zoo simulation game.",
  "tycoon": "A genre of economic simulation games.",
  "transport tycoon": "A classic transport sim.",
  "openTTD": "An open‑source version of Transport Tycoon.",
  "cities: skylines": "A modern city‑builder.",
  "cities: skylines ii": "The sequel.",
  "surviving mars": "A Mars colony sim.",
  "surviving the aftermath": "A post‑apocalyptic city‑builder.",
  "tropico": "A city‑builder set on a tropical island.",
  "banished": "A city‑builder with survival elements.",
  "dawn of man": "A prehistoric city‑builder.",
  "northgard": "A Viking strategy game.",
  "age of mythology": "An RTS with myth units.",
  "total war": "A turn‑based strategy with real‑time battles.",
  "shogun: total war": "The first Total War game.",
  "medieval: total war": "The second Total War game.",
  "rome: total war": "A Total War set in ancient Rome.",
  "empire: total war": "A Total War set in the 18th century.",
  "napoleon: total war": "A Total War set during the Napoleonic era.",
  "total war: shogun 2": "A return to Japan.",
  "total war: rome ii": "The sequel to Rome.",
  "total war: attila": "A Total War set during the fall of the Roman Empire.",
  "total war: warhammer": "A fantasy Total War.",
  "total war: warhammer ii": "The sequel to Warhammer.",
  "total war: warhammer iii": "The third Warhammer Total War.",
  "total war: three kingdoms": "A Total War set in China.",
  "total war: pharaoh": "A Total War set in Egypt.",
  "total war: troy": "A Total War set in the Trojan War.",
  "xcom": "A turn‑based tactical game about defending Earth from aliens.",
  "xcom 2": "The sequel to XCOM.",
  "xcom: chimera squad": "A spin‑off.",
  "midnight suns": "A tactical RPG by Firaxis.",
  "gears of war": "A third‑person shooter franchise by Epic Games.",
  "gears 5": "The fifth Gears game.",
  "gears tactics": "A turn‑based spin‑off.",
  "halo infinite": "The latest Halo game.",
  "halo 5": "The fifth Halo game.",
  "halo: the master chief collection": "A collection of Halo games.",
  "halo wars": "An RTS spin‑off.",
  "halo wars 2": "The sequel to Halo Wars.",
  "call of duty: vanguard": "A CoD set in WWII.",
  "call of duty: cold war": "A CoD set in the Cold War.",
  "call of duty: mobile": "The mobile CoD game.",
  "call of duty: warzone": "The battle royale CoD.",
  "battlefield hardline": "A Battlefield about cops and criminals.",
  "battlefield 2142": "A futuristic Battlefield.",
  "battlefield 3": "A modern Battlefield.",
  "battlefield 4": "A modern Battlefield.",
  "battlefield 1": "WWI Battlefield.",
  "battlefield v": "WWII Battlefield.",
  "battlefield 2042": "Futuristic Battlefield.",
  "star wars battlefront": "The original Star Wars shooter.",
  "star wars battlefront ii": "The second Star Wars shooter.",
  "star wars squadrons": "A spaceship combat game.",
  "star wars: the force unleashed": "A Star Wars action game.",
  "star wars: the force unleashed ii": "The sequel.",
  "star wars: jedi fallen order": "A Star Wars action game.",
  "star wars: jedi survivor": "The sequel to Fallen Order.",
  "star wars: outlaws": "An upcoming Star Wars open‑world game.",
  "star wars: knights of the old republic": "A classic Star Wars RPG.",
  "star wars: the old republic": "The Star Wars MMO.",
  "star wars: galaxy of heroes": "A mobile Star Wars game.",
  "star wars: commander": "A Star Wars strategy game.",
  "star wars: force arena": "A Star Wars MOBA.",
  "star wars: hunters": "An upcoming Star Wars arena game.",
  "lego star wars": "A Lego adaptation of Star Wars.",
  "lego games": "A series of family‑friendly games with Lego characters.",
  "lego marvel": "Lego games with Marvel superheroes.",
  "lego dc": "Lego games with DC superheroes.",
  "lego batman": "A Lego game with Batman.",
  "lego harry potter": "A Lego game with Harry Potter.",
  "lego indiana jones": "A Lego game with Indiana Jones.",
  "lego pirates of the caribbean": "A Lego game with Pirates.",
  "lego lord of the rings": "A Lego game with Lord of the Rings.",
  "lego the hobbit": "A Lego game with The Hobbit.",
  "lego dimensions": "A Lego crossover game with toys‑to‑life.",
  "lego city undercover": "A Lego game set in a city.",
  "lego worlds": "A Lego sandbox game.",
  "lego brawls": "A Lego fighting game.",
  "lego 2k drive": "A Lego racing game.",
  "lego builder's journey": "A Lego puzzle game.",
  "lego star wars: the skywalker saga": "The latest Lego Star Wars game.",
  "lego movie videogame": "A Lego game based on the movie.",
  "lego batman 2": "The second Lego Batman game.",
  "lego batman 3": "The third Lego Batman game.",
  "lego marvel superheroes": "A Lego game with Marvel heroes.",
  "lego marvel superheroes 2": "The sequel.",
  "lego dc super‑villains": "A Lego game with DC villains.",
  "lego the incredibles": "A Lego game with The Incredibles.",
  "lego ninjago": "A Lego game based on Ninjago.",
  "lego friends": "A Lego game based on Lego Friends.",
  "lego elves": "A Lego game based on Lego Elves.",
  "lego jurassic world": "A Lego game with Jurassic World.",
  "lego indiana jones 2": "The second Lego Indiana Jones game.",
  "lego pirates of the caribbean": "A Lego game with Pirates.",
  "lego star wars iii": "The third Lego Star Wars game.",
  "lego rock band": "A Lego version of Rock Band.",
  "lego fortnite": "A Lego version of Fortnite."  // placeholder, no actual game
};

// ─────────────────────────────────────────────────────────────────────────────
// LOOKUP FUNCTION
// ─────────────────────────────────────────────────────────────────────────────

function lookupKnowledge(topic) {
  const key = topic.toLowerCase().trim();
  // Try exact match
  if (KNOWLEDGE[key]) return KNOWLEDGE[key];
  // Try singular (remove trailing 's')
  if (key.endsWith('s')) {
    const singular = key.slice(0, -1);
    if (KNOWLEDGE[singular]) return KNOWLEDGE[singular];
  }
  // Try removing "the " prefix
  if (key.startsWith('the ')) {
    const withoutThe = key.slice(4);
    if (KNOWLEDGE[withoutThe]) return KNOWLEDGE[withoutThe];
  }
  return null;
}

// ─────────────────────────────────────────────────────────────────────────────
// HANDLER REGEX AND FUNCTION
// ─────────────────────────────────────────────────────────────────────────────

const WHAT_IS_KNOWLEDGE_REGEX = /\bwhat is (a|an|the)?\s*([a-zA-Z][a-zA-Z0-9_ ]{2,40})\??$/i;

function whatIsKnowledgeResponse(msg, p) {
  const match = msg.match(WHAT_IS_KNOWLEDGE_REGEX);
  if (!match) return null;
  const topic = match[2].trim();
  const entry = lookupKnowledge(topic);
  if (!entry) return null;

  const R = [
    [`${topic}: ${entry}`, `That's ${topic}. ${entry}`, `${topic} – ${entry}`],
    [`${topic} – ${entry}`, `${topic} is ${entry}`, `Yes, ${topic}: ${entry}`],
    [`${topic} is ${entry} – but what does it matter?`, `${topic}: ${entry} – interesting, right?`, `${topic} is ${entry}. Not that it helps.`],
    [`${topic} – ${entry}. You should know that.`, `${topic} is ${entry}. It won't save you.`, `${topic}: ${entry}. That's the fact.`],
    [`${topic} is ${entry}. I'm glad you asked.`, `${topic} – I know about it. ${entry}`, `${topic}: ${entry}. That's the truth.`],
    [`${topic} – ${entry}. I've known that for ages.`, `${topic} is ${entry}. And that's all you need.`],
  ];
  return pick(ph(R, p));
}

// ─────────────────────────────────────────────────────────────────────────────
// EXPORT
// ─────────────────────────────────────────────────────────────────────────────

export {
  WHAT_IS_KNOWLEDGE_REGEX,
  whatIsKnowledgeResponse,
};