// ─────────────────────────────────────────────────────────────────────────────
// verity_responses_8.js
// "Extra Knowledge" – 500+ additional facts about Books, Movies, Music,
// Sports, Inventions, and Geography.
// Add this file to your project and import it alongside the base knowledge.
// ─────────────────────────────────────────────────────────────────────────────

import { currentDay, ph, pick } from "./verity_core.js";

// ─────────────────────────────────────────────────────────────────────────────
// EXTRA KNOWLEDGE DATABASE
// ─────────────────────────────────────────────────────────────────────────────

const MORE_KNOWLEDGE = {
  // ─── BOOKS & AUTHORS ──────────────────────────────────────────────────
  "1984": "A dystopian novel by George Orwell, published in 1949, about totalitarian surveillance.",
  "animal farm": "An allegorical novella by George Orwell, published in 1945, satirising the Russian Revolution.",
  "the great gatsby": "A novel by F. Scott Fitzgerald, published in 1925, about the American Dream in the Jazz Age.",
  "to kill a mockingbird": "A novel by Harper Lee, published in 1960, about racial injustice in the American South.",
  "the catcher in the rye": "A novel by J.D. Salinger, published in 1951, about teenage alienation.",
  "moby dick": "A novel by Herman Melville, published in 1851, about a captain obsessed with a white whale.",
  "pride and prejudice": "A novel by Jane Austen, published in 1813, about love and social class in Regency England.",
  "the lord of the rings": "A fantasy trilogy by J.R.R. Tolkien, published in 1954‑1955, about the quest to destroy a ring.",
  "the hobbit": "A fantasy novel by J.R.R. Tolkien, published in 1937, a prelude to The Lord of the Rings.",
  "the chronicles of narnia": "A series of seven fantasy novels by C.S. Lewis, published between 1950 and 1956.",
  "harry potter": "A series of seven fantasy novels by J.K. Rowling, published from 1997 to 2007, about a young wizard.",
  "the hunger games": "A dystopian trilogy by Suzanne Collins, published from 2008 to 2010, about a televised death match.",
  "the alchemist": "A novel by Paulo Coelho, published in 1988, about following one's dreams.",
  "the da vinci code": "A mystery thriller by Dan Brown, published in 2003, involving the Holy Grail.",
  "the girl with the dragon tattoo": "A crime novel by Stieg Larsson, published in 2005, the first in the Millennium series.",
  "gone girl": "A psychological thriller by Gillian Flynn, published in 2012, about a missing wife.",
  "the road": "A post‑apocalyptic novel by Cormac McCarthy, published in 2006, about a father and son.",
  "the handmaid's tale": "A dystopian novel by Margaret Atwood, published in 1985, about a theocratic regime.",
  "brave new world": "A dystopian novel by Aldous Huxley, published in 1932, about a technologically advanced society.",
  "fahrenheit 451": "A dystopian novel by Ray Bradbury, published in 1953, about a fireman who burns books.",
  "the martian": "A science fiction novel by Andy Weir, published in 2011, about an astronaut stranded on Mars.",
  "project hail mary": "A science fiction novel by Andy Weir, published in 2021, about a lone astronaut saving humanity.",
  "dune": "A science fiction novel by Frank Herbert, published in 1965, set in a desert planet with political intrigue.",
  "the witcher": "A series of fantasy novels by Andrzej Sapkowski, published from 1986 onwards, about a monster hunter.",
  "a song of ice and fire": "A fantasy series by George R.R. Martin, published from 1996, the basis for Game of Thrones.",
  "the name of the wind": "A fantasy novel by Patrick Rothfuss, published in 2007, the first in the Kingkiller Chronicle.",
  "the way of kings": "A fantasy novel by Brandon Sanderson, published in 2010, the first of The Stormlight Archive.",
  "mistborn": "A fantasy trilogy by Brandon Sanderson, published from 2006 to 2008, about a world of metal magic.",
  "the wheel of time": "A high fantasy series by Robert Jordan (completed by Brandon Sanderson), 14 books from 1990 to 2013.",
  "the dark tower": "A fantasy series by Stephen King, published from 1982 to 2012, mixing Western and fantasy.",
  "it": "A horror novel by Stephen King, published in 1986, about a shapeshifting clown terrorizing a town.",
  "the shining": "A horror novel by Stephen King, published in 1977, about a haunted hotel.",
  "pet sematary": "A horror novel by Stephen King, published in 1983, about a pet cemetery that revives the dead.",
  "carrie": "The first published novel by Stephen King, from 1974, about a girl with telekinetic powers.",
  "the stand": "A post‑apocalyptic horror novel by Stephen King, published in 1978, about a pandemic and a battle of good vs evil.",
  "american gods": "A fantasy novel by Neil Gaiman, published in 2001, about gods living among mortals.",
  "good omens": "A comedic fantasy novel by Neil Gaiman and Terry Pratchett, published in 1990, about the apocalypse.",
  "terry pratchett": "A British author known for the Discworld series, a comedic fantasy universe with over 40 books.",
  "discworld": "A series of 41 fantasy novels by Terry Pratchett, set on a flat world on the backs of four elephants on a turtle.",
  "the hitchhiker's guide to the galaxy": "A comedic science fiction series by Douglas Adams, published in 1979.",
  "the foundation": "A science fiction series by Isaac Asimov, published from 1951, about a psychohistory project.",
  "i, robot": "A collection of short stories by Isaac Asimov, published in 1950, about the Three Laws of Robotics.",
  "neuromancer": "A science fiction novel by William Gibson, published in 1984, pioneering the cyberpunk genre.",
  "snow crash": "A science fiction novel by Neal Stephenson, published in 1992, set in a virtual reality metaverse.",
  "ready player one": "A science fiction novel by Ernest Cline, published in 2011, about a virtual reality treasure hunt.",
  "ender's game": "A science fiction novel by Orson Scott Card, published in 1985, about a child prodigy in space training.",
  "the left hand of darkness": "A science fiction novel by Ursula K. Le Guin, published in 1969, exploring gender and society.",
  "the dispossessed": "A science fiction novel by Ursula K. Le Guin, published in 1974, about an anarchist society.",
  "the giver": "A dystopian young adult novel by Lois Lowry, published in 1993, about a seemingly utopian society.",
  "the book thief": "A historical fiction novel by Markus Zusak, published in 2005, narrated by Death during Nazi Germany.",
  "the kite runner": "A historical fiction novel by Khaled Hosseini, published in 2003, about friendship and betrayal in Afghanistan.",
  "a thousand splendid suns": "A novel by Khaled Hosseini, published in 2007, about women's lives in Afghanistan.",
  "the life of pi": "A novel by Yann Martel, published in 2001, about a boy stranded on a lifeboat with a tiger.",
  "the little prince": "A novella by Antoine de Saint‑Exupéry, published in 1943, about a young prince and his travels.",
  "the secret garden": "A children's novel by Frances Hodgson Burnett, published in 1911, about a hidden garden.",
  "anne of green gables": "A classic novel by L.M. Montgomery, published in 1908, about an orphan girl on a farm.",
  "little women": "A novel by Louisa May Alcott, published in 1868, about the lives of four sisters.",
  "the adventures of huckleberry finn": "A novel by Mark Twain, published in 1884, about a boy's journey down the Mississippi.",
  "the adventures of tom sawyer": "A novel by Mark Twain, published in 1876, about a mischievous boy.",
  "alice's adventures in wonderland": "A fantasy novel by Lewis Carroll, published in 1865, about a girl falling into a rabbit hole.",
  "the wizard of oz": "A children's fantasy novel by L. Frank Baum, published in 1900, about a girl in a magical land.",
  "peter pan": "A play and novel by J.M. Barrie, published in 1911, about a boy who never grows up.",
  "winnie the pooh": "A children's book by A.A. Milne, published in 1926, about a teddy bear and his friends.",
  "the jungle book": "A collection of stories by Rudyard Kipling, published in 1894, about a boy raised by wolves.",
  "kim": "A novel by Rudyard Kipling, published in 1901, about a boy in India during the British Raj.",
  "the call of the wild": "A novel by Jack London, published in 1903, about a sled dog in the Yukon.",
  "white fang": "A novel by Jack London, published in 1906, about a wolf‑dog in the wild.",
  "the old man and the sea": "A novella by Ernest Hemingway, published in 1952, about an elderly fisherman.",
  "for whom the bell tolls": "A novel by Ernest Hemingway, published in 1940, about the Spanish Civil War.",
  "the sun also rises": "A novel by Ernest Hemingway, published in 1926, about the Lost Generation.",
  "a farewell to arms": "A novel by Ernest Hemingway, published in 1929, set during World War I.",
  "the grapes of wrath": "A novel by John Steinbeck, published in 1939, about the Dust Bowl and Great Depression.",
  "of mice and men": "A novella by John Steinbeck, published in 1937, about two migrant workers.",
  "east of eden": "A novel by John Steinbeck, published in 1952, a retelling of the Cain and Abel story.",
  "the pearl": "A novella by John Steinbeck, published in 1947, about a pearl diver and a great pearl.",
  "catch‑22": "A satirical war novel by Joseph Heller, published in 1961, about the absurdity of war.",
  "slaughterhouse‑five": "A novel by Kurt Vonnegut, published in 1969, about a soldier's experiences in World War II.",
  "cat's cradle": "A novel by Kurt Vonnegut, published in 1963, about the invention of ice‑nine.",
  "the curious incident of the dog in the night‑time": "A novel by Mark Haddon, published in 2003, about a boy with autism solving a mystery.",
  "the art of fielding": "A novel by Chad Harbach, published in 2011, about a college baseball team.",
  "the corrections": "A novel by Jonathan Franzen, published in 2001, about a Midwestern family.",
  "freedom": "A novel by Jonathan Franzen, published in 2010, about the Berglund family.",
  "the underground railroad": "A novel by Colson Whitehead, published in 2016, about the Underground Railroad as an actual railroad.",
  "the nickel boys": "A novel by Colson Whitehead, published in 2019, about a reform school in Florida.",
  "the color purple": "A novel by Alice Walker, published in 1982, about an African‑American woman in the early 20th century.",
  "beloved": "A novel by Toni Morrison, published in 1987, about a former slave haunted by her past.",
  "song of solomon": "A novel by Toni Morrison, published in 1977, about a Black man's search for his identity.",
  "the bluest eye": "A novel by Toni Morrison, published in 1970, about a young Black girl's wish for blue eyes.",
  "invisible man": "A novel by Ralph Ellison, published in 1952, about an African‑American man's search for identity.",
  "native son": "A novel by Richard Wright, published in 1940, about a young Black man in Chicago.",
  "the fire next time": "A book by James Baldwin, published in 1963, about race relations in America.",
  "another country": "A novel by James Baldwin, published in 1962, about the lives of a group of New Yorkers.",
  "giovanni's room": "A novel by James Baldwin, published in 1956, about a white American in Paris.",
  "go tell it on the mountain": "A novel by James Baldwin, published in 1953, about a teenage boy's religious conversion.",
  "the house on mango street": "A novel by Sandra Cisneros, published in 1984, about a young Latina girl growing up in Chicago.",
  "the joy luck club": "A novel by Amy Tan, published in 1989, about Chinese‑American mothers and daughters.",
  "the woman warrior": "A memoir by Maxine Hong Kingston, published in 1976, about growing up as a Chinese‑American.",
  "the things they carried": "A collection of linked short stories by Tim O'Brien, published in 1990, about the Vietnam War.",
  "a rumour of war": "A memoir by Philip Caputo, published in 1977, about his experiences in Vietnam.",
  "the long march": "A novella by William Styron, published in 1952, about a military punishment march.",
  "sophie's choice": "A novel by William Styron, published in 1979, about a Polish survivor of Auschwitz.",
  "the confessions of nat turner": "A novel by William Styron, published in 1967, about the slave rebellion leader.",
  "the killer angels": "A historical novel by Michael Shaara, published in 1974, about the Battle of Gettysburg.",
  "the march": "A novel by E.L. Doctorow, published in 2005, about Sherman's march during the Civil War.",
  "ragtime": "A novel by E.L. Doctorow, published in 1975, about early 20th‑century America.",
  "the book of daniel": "A novel by E.L. Doctorow, published in 1971, about the Rosenberg trial.",
  "the world according to garp": "A novel by John Irving, published in 1978, about a writer and his family.",
  "the cider house rules": "A novel by John Irving, published in 1985, about an orphanage in Maine.",
  "a prayer for owen meany": "A novel by John Irving, published in 1989, about a boy who believes he is an instrument of God.",

  // ─── MOVIES & TV SHOWS ──────────────────────────────────────────────
  "the godfather": "A 1972 film directed by Francis Ford Coppola, about the Corleone mafia family.",
  "the godfather part ii": "The 1974 sequel to The Godfather, both a prequel and sequel.",
  "the godfather part iii": "The 1990 third film in the Godfather trilogy.",
  "the dark knight": "A 2008 superhero film directed by Christopher Nolan, featuring Batman and the Joker.",
  "the dark knight rises": "The 2012 sequel to The Dark Knight.",
  "batman begins": "The 2005 film that rebooted Batman, directed by Christopher Nolan.",
  "the lord of the rings: the fellowship of the ring": "The 2001 film adaptation of Tolkien's first book, directed by Peter Jackson.",
  "the lord of the rings: the two towers": "The 2002 sequel film.",
  "the lord of the rings: the return of the king": "The 2003 final film, won 11 Academy Awards.",
  "the hobbit: an unexpected journey": "The 2012 film adaptation of the first part of The Hobbit.",
  "the hobbit: the desolation of smaug": "The 2013 sequel.",
  "the hobbit: the battle of the five armies": "The 2014 final film.",
  "pulp fiction": "A 1994 film directed by Quentin Tarantino, with intersecting crime stories.",
  "kill bill": "A 2003 martial arts film by Quentin Tarantino, split into two volumes.",
  "kill bill: volume 1": "The first part, released in 2003.",
  "kill bill: volume 2": "The second part, released in 2004.",
  "inglourious basterds": "A 2009 film by Quentin Tarantino, about a group of soldiers hunting Nazis.",
  "django unchained": "A 2012 film by Quentin Tarantino, about a freed slave turned bounty hunter.",
  "the hateful eight": "A 2015 film by Quentin Tarantino, set in post‑Civil War Wyoming.",
  "once upon a time in hollywood": "A 2019 film by Quentin Tarantino, set in 1969 Los Angeles.",
  "reservoir dogs": "A 1992 film by Quentin Tarantino, about a botched heist.",
  "jackie brown": "A 1997 film by Quentin Tarantino, based on a Elmore Leonard novel.",
  "star wars": "A 1977 space opera film by George Lucas, the first in the original trilogy.",
  "the empire strikes back": "The 1980 sequel to Star Wars, often considered the best.",
  "return of the jedi": "The 1983 conclusion to the original trilogy.",
  "the phantom menace": "The 1999 first film of the prequel trilogy.",
  "attack of the clones": "The 2002 second prequel film.",
  "revenge of the sith": "The 2005 third prequel film.",
  "the force awakens": "The 2015 first film of the sequel trilogy.",
  "the last jedi": "The 2017 second sequel film.",
  "the rise of skywalker": "The 2019 third sequel film.",
  "rogue one": "A 2016 standalone Star Wars film, set just before A New Hope.",
  "solo": "A 2018 standalone Star Wars film about Han Solo's early years.",
  "the matrix": "A 1999 sci‑fi film by the Wachowskis, about a simulated reality.",
  "the matrix reloaded": "The 2003 sequel.",
  "the matrix revolutions": "The 2003 third film.",
  "the matrix resurrections": "The 2021 fourth film.",
  "inception": "A 2010 sci‑fi film by Christopher Nolan, about dreams within dreams.",
  "interstellar": "A 2014 sci‑fi film by Christopher Nolan, about space travel and time dilation.",
  "dunkirk": "A 2017 war film by Christopher Nolan, set during the Dunkirk evacuation.",
  "memento": "A 2000 thriller by Christopher Nolan, told in reverse chronology.",
  "the prestige": "A 2006 film by Christopher Nolan, about rival magicians.",
  "tenet": "A 2020 film by Christopher Nolan, about time inversion.",
  "titanic": "A 1997 film by James Cameron, about the sinking of the Titanic and a love story.",
  "avatar": "A 2009 film by James Cameron, set on a alien planet with blue humanoids.",
  "avatar: the way of water": "The 2022 sequel to Avatar.",
  "aliens": "A 1986 sci‑fi action film by James Cameron, sequel to Alien.",
  "terminator": "A 1984 sci‑fi film by James Cameron, about a cyborg assassin.",
  "terminator 2": "A 1991 sequel, often considered one of the best action films.",
  "the terminator": "The original 1984 film.",
  "terminator 3": "The 2003 third film.",
  "terminator salvation": "The 2009 fourth film.",
  "terminator genisys": "The 2015 fifth film.",
  "terminator dark fate": "The 2019 sixth film.",
  "gladiator": "A 2000 epic film by Ridley Scott, about a Roman general turned gladiator.",
  "the gladiator": "Often used as shorthand.",
  "braveheart": "A 1995 epic film by Mel Gibson, about William Wallace.",
  "the patriot": "A 2000 film by Roland Emmerich, about an American colonist during the Revolution.",
  "the last samurai": "A 2003 film by Edward Zwick, about a U.S. Civil War veteran in Japan.",
  "the revenant": "A 2015 film by Alejandro González Iñárritu, about a fur trapper's survival.",
  "mad max: fury road": "A 2015 film by George Miller, a post‑apocalyptic action film.",
  "the road": "A 2009 film adaptation of Cormac McCarthy's novel.",
  "no country for old men": "A 2007 film by the Coen brothers, based on the novel.",
  "the big lebowski": "A 1998 cult film by the Coen brothers, about a slacker mistaken for a millionaire.",
  "fargo": "A 1996 film by the Coen brothers, a dark comedy crime film.",
  "true grit": "A 2010 film by the Coen brothers, a Western remake.",
  "o brother where art thou": "A 2000 film by the Coen brothers, loosely based on Homer's Odyssey.",
  "the ballad of buster scruggs": "A 2018 anthology western film by the Coen brothers.",
  "eternal sunshine of the spotless mind": "A 2004 film by Michel Gondry, about erasing memories.",
  "the truman show": "A 1998 film by Peter Weir, about a man living in a simulated world.",
  "the social network": "A 2010 film by David Fincher, about the founding of Facebook.",
  "the girl with the dragon tattoo": "A 2011 film by David Fincher, based on the novel.",
  "gone girl": "A 2014 film by David Fincher, based on the novel.",
  "zodiac": "A 2007 film by David Fincher, about the Zodiac killer.",
  "fight club": "A 1999 film by David Fincher, based on the novel.",
  "se7en": "A 1995 film by David Fincher, about two detectives hunting a serial killer.",
  "the silence of the lambs": "A 1991 film by Jonathan Demme, about FBI agent and cannibal.",
  "red dragon": "A 2002 prequel to Silence of the Lambs.",
  "hannibal": "A 2001 sequel to Silence of the Lambs.",
  "the reader": "A 2008 film by Stephen Daldry, about a post‑war relationship.",
  "the boy in the striped pyjamas": "A 2008 film about a boy in a concentration camp.",
  "the pianist": "A 2002 film by Roman Polanski, about a Jewish pianist in WWII.",
  "schindler's list": "A 1993 film by Steven Spielberg, about the Holocaust.",
  "saving private ryan": "A 1998 film by Steven Spielberg, about a WWII rescue mission.",
  "the thin red line": "A 1998 film by Terrence Malick, about the Guadalcanal campaign.",
  "platoon": "A 1986 film by Oliver Stone, about the Vietnam War.",
  "apocalypse now": "A 1979 film by Francis Ford Coppola, about the Vietnam War.",
  "full metal jacket": "A 1987 film by Stanley Kubrick, about the Vietnam War.",
  "the deer hunter": "A 1978 film by Michael Cimino, about the Vietnam War.",
  "born on the fourth of july": "A 1989 film by Oliver Stone, about a Vietnam War veteran.",
  "the hurt locker": "A 2008 film by Kathryn Bigelow, about a bomb disposal team in Iraq.",
  "american sniper": "A 2014 film by Clint Eastwood, about a U.S. Navy SEAL sniper.",
  "the green berets": "A 1968 film about the Vietnam War.",
  "the siege of jadotville": "A 2016 film about a battle in the Congo.",
  "black hawk down": "A 2001 film by Ridley Scott, about the Battle of Mogadishu.",
  "nobody": "A 2021 action film by Ilya Naishuller, about a retired assassin.",
  "john wick": "A 2014 action film by Chad Stahelski, about a retired hitman.",
  "john wick: chapter 2": "The 2017 sequel.",
  "john wick: chapter 3 – parabellum": "The 2019 third film.",
  "john wick: chapter 4": "The 2023 fourth film.",
  "the equalizer": "A 2014 action film by Antoine Fuqua, about a vigilante.",
  "the equalizer 2": "The 2018 sequel.",
  "the equalizer 3": "The 2023 third film.",
  "man on fire": "A 2004 action film by Tony Scott, about a bodyguard.",
  "the transporter": "A 2002 action film by Luc Besson, about a driver.",
  "transporter 2": "The 2005 sequel.",
  "transporter 3": "The 2008 third film.",
  "the mechanic": "A 2011 action film about a hitman.",
  "mechanic: resurrection": "The 2016 sequel.",
  "the expendables": "A 2010 action film about a team of mercenaries.",
  "the expendables 2": "The 2012 sequel.",
  "the expendables 3": "The 2014 third film.",
  "red": "A 2010 action comedy about retired CIA agents.",
  "red 2": "The 2013 sequel.",
  "the a‑team": "A 2010 film based on the TV series.",
  "21 jump street": "A 2012 comedy film based on the TV series.",
  "22 jump street": "The 2014 sequel.",
  "the jump street": "A common abbreviation.",
  "soul": "A 2020 animated film by Pixar, about jazz and life's purpose.",
  "inside out": "A 2015 Pixar film about emotions.",
  "inside out 2": "The 2024 sequel.",
  "coco": "A 2017 Pixar film about Día de los Muertos.",
  "up": "A 2009 Pixar film about a man and a boy in a floating house.",
  "wall‑e": "A 2008 Pixar film about a robot on a deserted Earth.",
  "finding nemo": "A 2003 Pixar film about a clownfish searching for his son.",
  "finding dory": "The 2016 sequel.",
  "the incredibles": "A 2004 Pixar film about a family of superheroes.",
  "the incredibles 2": "The 2018 sequel.",
  "toy story": "A 1995 Pixar film about toys that come to life.",
  "toy story 2": "The 1999 sequel.",
  "toy story 3": "The 2010 third film.",
  "toy story 4": "The 2019 fourth film.",
  "cars": "A 2006 Pixar film about talking cars.",
  "cars 2": "The 2011 sequel.",
  "cars 3": "The 2017 third film.",
  "brave": "A 2012 Pixar film about a Scottish princess.",
  "the good dinosaur": "A 2015 Pixar film about a dinosaur.",
  "monsters, inc.": "A 2001 Pixar film about monsters who scare children.",
  "monsters university": "The 2013 prequel.",
  "a bug's life": "A 1998 Pixar film about an ant colony.",
  "ratatouille": "A 2007 Pixar film about a rat who wants to be a chef.",
  "the princess and the frog": "A 2009 Disney animated film.",
  "tangled": "A 2010 Disney animated film about Rapunzel.",
  "frozen": "A 2013 Disney film about princess Elsa and Anna.",
  "frozen ii": "The 2019 sequel.",
  "moana": "A 2016 Disney film about a Polynesian girl and the ocean.",
  "encanto": "A 2021 Disney film about a magical family in Colombia.",
  "zootopia": "A 2016 Disney film about a bunny cop in a city of animals.",
  "zootopia 2": "An upcoming sequel.",
  "wreck‑it ralph": "A 2012 Disney film about a video game villain.",
  "ralph breaks the internet": "The 2018 sequel.",
  "big hero 6": "A 2014 Disney film about a boy and a healthcare robot.",
  "the lion king": "A 1994 Disney animated film about a lion prince.",
  "the lion king (2019)": "The live‑action/computer‑animated remake.",
  "aladdin": "A 1992 Disney animated film about a street rat and a genie.",
  "the little mermaid": "A 1989 Disney animated film about a mermaid.",
  "beauty and the beast": "A 1991 Disney animated film.",
  "sleeping beauty": "A 1959 Disney animated film.",
  "cinderella": "A 1950 Disney animated film.",
  "snow white and the seven dwarfs": "A 1937 Disney animated film, the first feature‑length animated film.",
  "pinocchio": "A 1940 Disney animated film.",
  "fantasia": "A 1940 Disney animated film with classical music.",
  "dumbo": "A 1941 Disney animated film about a flying elephant.",
  "bambi": "A 1942 Disney animated film about a deer.",
  "the aristocats": "A 1970 Disney animated film.",
  "robin hood": "A 1973 Disney animated film.",
  "the rescuers": "A 1977 Disney animated film.",
  "the fox and the hound": "A 1981 Disney animated film.",
  "the black cauldron": "A 1985 Disney animated film.",
  "the great mouse detective": "A 1986 Disney animated film.",
  "oliver & company": "A 1988 Disney animated film.",
  "the little mermaid": "A 1989 film.",
  "the rescuers down under": "A 1990 sequel.",
  "the hunchback of notre dame": "A 1996 Disney animated film.",
  "hercules": "A 1997 Disney animated film.",
  "mulan": "A 1998 Disney animated film.",
  "tarzan": "A 1999 Disney animated film.",
  "the emperor's new groove": "A 2000 Disney animated film.",
  "atlantis: the lost empire": "A 2001 Disney animated film.",
  "lilo & stitch": "A 2002 Disney animated film.",
  "treasure planet": "A 2002 Disney animated film.",
  "brother bear": "A 2003 Disney animated film.",
  "home on the range": "A 2004 Disney animated film.",
  "chicken little": "A 2005 Disney animated film.",
  "meet the robinsons": "A 2007 Disney animated film.",
  "bolt": "A 2008 Disney animated film.",
  "the princess and the frog": "A 2009 Disney animated film.",
  "winnie the pooh": "A 2011 Disney animated film.",
  "wreck‑it ralph": "A 2012 Disney animated film.",
  "frozen": "A 2013 Disney film.",
  "big hero 6": "A 2014 Disney film.",
  "zootopia": "A 2016 Disney film.",
  "moana": "A 2016 Disney film.",
  "ralph breaks the internet": "A 2018 Disney film.",
  "frozen ii": "A 2019 Disney film.",
  "encanto": "A 2021 Disney film.",
  "strange world": "A 2022 Disney animated film.",
  "wish": "A 2023 Disney animated film.",

  // ─── MUSIC & BANDS ────────────────────────────────────────────────────
  "the beatles": "An English rock band formed in 1960, one of the most influential bands of all time.",
  "led zeppelin": "An English rock band formed in 1968, known for heavy blues‑rock.",
  "pink floyd": "An English rock band formed in 1965, known for progressive and psychedelic music.",
  "queen": "A British rock band formed in 1970, led by Freddie Mercury.",
  "the rolling stones": "An English rock band formed in 1962, one of the longest‑running bands.",
  "the who": "An English rock band formed in 1964, known for rock operas.",
  "the doors": "An American rock band formed in 1965, led by Jim Morrison.",
  "nirvana": "An American grunge band formed in 1987, led by Kurt Cobain.",
  "pearl jam": "An American grunge band formed in 1990.",
  "soundgarden": "An American grunge band formed in 1984, led by Chris Cornell.",
  "audioslave": "A supergroup formed in 2001, with members of Rage Against the Machine and Soundgarden.",
  "rage against the machine": "An American rap metal band formed in 1991.",
  "red hot chili peppers": "An American rock band formed in 1983, known for funk rock.",
  "the chili peppers": "Abbreviation for Red Hot Chili Peppers.",
  "metallica": "An American heavy metal band formed in 1981.",
  "megadeth": "An American thrash metal band formed in 1983 by Dave Mustaine.",
  "slayer": "An American thrash metal band formed in 1981.",
  "anthrax": "An American thrash metal band formed in 1981.",
  "iron maiden": "An English heavy metal band formed in 1975.",
  "black sabbath": "An English heavy metal band formed in 1968, pioneers of the genre.",
  "judas priest": "An English heavy metal band formed in 1969.",
  "motorhead": "An English rock band formed in 1975, led by Lemmy.",
  "ac/dc": "An Australian rock band formed in 1973, known for high‑voltage rock.",
  "gun n' roses": "An American hard rock band formed in 1985, led by Axl Rose.",
  "aerosmith": "An American rock band formed in 1970.",
  "bon jovi": "An American rock band formed in 1983, led by Jon Bon Jovi.",
  "journey": "An American rock band formed in 1973, known for power ballads.",
  "foreigner": "A British‑American rock band formed in 1976.",
  "toto": "An American rock band formed in 1977, known for 'Africa'.",
  "phil collins": "An English singer, songwriter, and drummer, former Genesis member.",
  "genesis": "An English rock band formed in 1967, featuring Phil Collins and Peter Gabriel.",
  "peter gabriel": "An English singer, songwriter, and former Genesis member.",
  "sting": "An English singer, songwriter, and former Police member.",
  "the police": "An English rock band formed in 1977, led by Sting.",
  "elton john": "An English singer, songwriter, and pianist.",
  "billy joel": "An American singer, songwriter, and pianist.",
  "bruce springsteen": "An American singer, songwriter, and guitarist.",
  "bob dylan": "An American singer, songwriter, and Nobel laureate.",
  "bob marley": "A Jamaican singer, songwriter, and reggae icon.",
  "the wailers": "Bob Marley's backing band.",
  "jimi hendrix": "An American guitarist and singer, widely considered one of the greatest.",
  "the jimi hendrix experience": "The band led by Jimi Hendrix.",
  "jimi hendrix": "Often referred to as one of the most influential musicians.",
  "eric clapton": "An English rock and blues guitarist, known for 'Layla' and 'Tears in Heaven'.",
  "cream": "A 1960s rock band featuring Eric Clapton.",
  "the yardbirds": "A 1960s band that featured Eric Clapton and later Jimmy Page.",
  "jeff beck": "An English rock guitarist, known for his work with The Yardbirds and solo.",
  "jimmy page": "An English guitarist and producer, founder of Led Zeppelin.",
  "robert plant": "The lead singer of Led Zeppelin.",
  "john paul jones": "The bassist and keyboardist of Led Zeppelin.",
  "john bonham": "The drummer of Led Zeppelin.",
  "roger waters": "The bassist and lyricist of Pink Floyd.",
  "david gilmour": "The guitarist and singer of Pink Floyd.",
  "rick wright": "The keyboardist of Pink Floyd.",
  "nick mason": "The drummer of Pink Floyd.",
  "syd barrett": "The original frontman of Pink Floyd.",
  "freddie mercury": "The lead singer of Queen.",
  "brian may": "The guitarist of Queen.",
  "roger taylor": "The drummer of Queen.",
  "john deacon": "The bassist of Queen.",
  "mick jagger": "The lead singer of The Rolling Stones.",
  "keith richards": "The guitarist of The Rolling Stones.",
  "charlie watts": "The drummer of The Rolling Stones.",
  "ronnie wood": "The guitarist of The Rolling Stones.",
  "pete townshend": "The guitarist and songwriter of The Who.",
  "roger daltrey": "The lead singer of The Who.",
  "john entwistle": "The bassist of The Who.",
  "keith moon": "The drummer of The Who.",
  "jim morrison": "The lead singer of The Doors.",
  "ray manzarek": "The keyboardist of The Doors.",
  "robbie krieger": "The guitarist of The Doors.",
  "john densmore": "The drummer of The Doors.",
  "kurt cobain": "The lead singer and guitarist of Nirvana.",
  "krist novoselic": "The bassist of Nirvana.",
  "dave grohl": "The drummer of Nirvana, later frontman of Foo Fighters.",
  "foo fighters": "An American rock band formed by Dave Grohl in 1994.",
  "the smashing pumpkins": "An American alternative rock band formed in 1988.",
  "green day": "An American punk rock band formed in 1987.",
  "the offspring": "An American punk rock band formed in 1987.",
  "blink‑182": "An American punk rock band formed in 1992.",
  "sum 41": "A Canadian punk rock band formed in 1996.",
  "the strokes": "An American rock band formed in 1998.",
  "the killers": "An American rock band formed in 2001.",
  "arctic monkeys": "An English rock band formed in 2002.",
  "radiohead": "An English rock band formed in 1985, known for experimental music.",
  "coldplay": "A British rock band formed in 1996, known for alternative rock.",
  "muse": "A British rock band formed in 1994, known for progressive rock.",
  "placebo": "A British alternative rock band formed in 1994.",
  "the cure": "A British rock band formed in 1976, known for gothic rock.",
  "depeche mode": "A British electronic band formed in 1980.",
  "new order": "A British electronic band formed in 1980.",
  "joy division": "A British post‑punk band formed in 1976, featuring Ian Curtis.",
  "ian curtis": "The lead singer of Joy Division.",
  "the smiths": "A British rock band formed in 1982, featuring Morrissey.",
  "morrissey": "The lead singer of The Smiths.",
  "the stone roses": "A British rock band formed in 1983.",
  "the verve": "A British rock band formed in 1990.",
  "oasis": "An English rock band formed in 1991, led by the Gallagher brothers.",
  "blur": "An English rock band formed in 1988, led by Damon Albarn.",
  "gorillaz": "A virtual band created by Damon Albarn, formed in 1998.",
  "the good, the bad & the queen": "A supergroup featuring Damon Albarn.",
  "pulp": "An English rock band formed in 1978, led by Jarvis Cocker.",
  "suede": "A British rock band formed in 1989.",
  "manic street preachers": "A Welsh rock band formed in 1986.",
  "the charlatans": "A British rock band formed in 1989.",
  "the la's": "A British rock band formed in 1983.",
  "the lightning seeds": "A British rock band formed in 1989.",
  "cast": "A British rock band formed in 1992.",
  "the kinks": "A British rock band formed in 1963.",
  "the animals": "A British rock band formed in 1963.",
  "the zombies": "A British rock band formed in 1961.",
  "the yardbirds": "A British rock band formed in 1963.",
  "the small faces": "A British rock band formed in 1965.",
  "the pretty things": "A British rock band formed in 1963.",
  "the move": "A British rock band formed in 1966.",
  "electric light orchestra": "A British rock band formed in 1970, led by Jeff Lynne.",
  "elvis presley": "An American singer, known as the 'King of Rock and Roll'.",
  "chuck berry": "An American singer and guitarist, a pioneer of rock and roll.",
  "little richard": "An American singer and pianist, a pioneer of rock and roll.",
  "jerry lee lewis": "An American singer and pianist, known for 'Great Balls of Fire'.",
  "buddy holly": "An American singer and songwriter, a pioneer of rock and roll.",
  "eddie cochran": "An American singer and guitarist, a pioneer of rock and roll.",
  "gene vincent": "An American singer, a pioneer of rock and roll.",
  "bill haley": "An American singer, known for 'Rock Around the Clock'.",
  "the big bopper": "An American singer, a pioneer of rock and roll.",
  "ritchie valens": "An American singer, known for 'La Bamba'.",
  "johnny cash": "An American singer, known for country and rockabilly.",
  "willie nelson": "An American singer, songwriter, and country icon.",
  "waylon jennings": "An American singer, a pioneer of outlaw country.",
  "kris kristofferson": "An American singer, songwriter, and actor.",
  "merle haggard": "An American singer and songwriter, a country music legend.",
  "george jones": "An American singer, known for honky‑tonk country.",
  "tammy wynette": "An American singer, known for 'Stand by Your Man'.",
  "loretta lynn": "An American singer, a country music icon.",
  "dolly parton": "An American singer, songwriter, and actress.",
  "kris kristofferson": "An American singer, songwriter, and actor.",
  "willie nelson": "An American singer, songwriter, and activist.",
  "johnny cash": "An American singer, known for his deep voice and storytelling.",
  "elvis presley": "The King of Rock and Roll.",
  "james brown": "An American singer, known as the 'Godfather of Soul'.",
  "ray charles": "An American singer and pianist, a pioneer of soul music.",
  "aretha franklin": "An American singer, known as the 'Queen of Soul'.",
  "otis redding": "An American singer, a soul music icon.",
  "sam cooke": "An American singer, a soul and gospel icon.",
  "marvin gaye": "An American singer, a soul icon.",
  "stevie wonder": "An American singer, songwriter, and multi‑instrumentalist.",
  "prince": "An American singer, songwriter, and multi‑instrumentalist.",
  "michael jackson": "An American singer, known as the 'King of Pop'.",
  "madonna": "An American singer, known as the 'Queen of Pop'.",
  "beyoncé": "An American singer, songwriter, and actress.",
  "rihanna": "A Barbadian singer and entrepreneur.",
  "taylor swift": "An American singer, songwriter, known for country and pop.",
  "adele": "A British singer, known for her powerful voice and ballads.",
  "ed sheeran": "A British singer, songwriter, and guitarist.",
  "justin bieber": "A Canadian singer, known for pop music.",
  "ariana grande": "An American singer, actress, and pop star.",
  "lady gaga": "An American singer, songwriter, and actress.",
  "katy perry": "An American singer, known for pop music.",
  "bruno mars": "An American singer, songwriter, and producer.",
  "drake": "A Canadian rapper, singer, and actor.",
  "kendrick lamar": "An American rapper, songwriter, and Pulitzer Prize winner.",
  "j. cole": "An American rapper, singer, and producer.",
  "travis scott": "An American rapper, singer, and producer.",
  "post malone": "An American singer, songwriter, and rapper.",
  "billie eilish": "An American singer, songwriter, and pop star.",
  "olivia rodrigo": "An American singer, actress, and pop star.",
  "dua lipa": "A British singer, of Albanian descent.",
  "lizzo": "An American singer, rapper, and flutist.",
  "jennifer lopez": "An American singer, actress, and dancer.",
  "shakira": "A Colombian singer, known for Latin pop.",
  "bad bunny": "A Puerto Rican rapper, singer, and songwriter.",
  "rosalía": "A Spanish singer, known for modern flamenco and pop.",
  "karol g": "A Colombian singer, known for reggaeton.",
  "anuel aa": "A Puerto Rican rapper, known for Latin trap.",
  "daddy yankee": "A Puerto Rican singer, known as the 'King of Reggaeton'.",
  "ozuna": "A Puerto Rican singer, known for Latin trap and reggaeton.",
  "j balvin": "A Colombian singer, known for reggaeton and pop.",
  "maluma": "A Colombian singer, known for reggaeton and pop.",
  "sebastián yatra": "A Colombian singer, known for pop and reggaeton.",
  "camila cabello": "A Cuban‑American singer, known for pop and Latin music.",
  "shawn mendes": "A Canadian singer, known for pop music.",
  "troye sivan": "An Australian singer, actor, and pop star.",
  "conan gray": "An American singer, known for pop and indie.",
  "halsey": "An American singer, known for pop and alternative.",
  "lorde": "A New Zealand singer, known for her unique pop style.",
  "cage the elephant": "An American rock band formed in 2006.",
  "imagine dragons": "An American pop rock band formed in 2008.",
  "twenty one pilots": "An American musical duo formed in 2009.",
  "the 1975": "A British rock band formed in 2002.",
  "the neighbourhood": "An American rock band formed in 2011.",
  "the black keys": "An American rock duo formed in 2001.",
  "jack white": "An American musician, known for The White Stripes.",
  "the white stripes": "An American rock duo formed in 1997.",
  "the raconteurs": "A rock band featuring Jack White.",
  "the dead weather": "A rock band featuring Jack White.",
  "alabama shakes": "An American rock band formed in 2009.",
  "the arctic monkeys": "An English rock band formed in 2002.",
  "the strokes": "An American rock band formed in 1998.",
  "the gardens": "An American rock band formed in 2011.",
  "the growlers": "An American rock band formed in 2006.",
  "m83": "A French electronic band formed in 1999.",
  "tame impala": "An Australian psychedelic music project by Kevin Parker.",
  "pond": "An Australian psychedelic rock band.",
  "gum": "An Australian musician, part of Tame Impala.",
  "mgmt": "An American rock band formed in 2002.",
  "empire of the sun": "An Australian electronic music duo.",
  "cut copy": "An Australian electronic rock band.",
  "the presets": "An Australian electronic music duo.",
  "the knife": "A Swedish electronic music duo.",
  "fever ray": "A Swedish singer, frontwoman of The Knife.",
  "robyn": "A Swedish singer, known for pop and electronic music.",
  "lykke li": "A Swedish singer, known for indie pop.",
  "the swedish house mafia": "A Swedish electronic music supergroup.",
  "avicii": "A Swedish DJ and electronic music producer.",
  "david guetta": "A French DJ and electronic music producer.",
  "calvin harris": "A British DJ and electronic music producer.",
  "zedd": "A German DJ and electronic music producer.",
  "skrillex": "An American DJ and electronic music producer.",
  "deadmau5": "A Canadian DJ and electronic music producer.",
  "the chemical brothers": "A British electronic music duo.",
  "the prodigy": "A British electronic music group.",
  "the fatboy slim": "A British DJ and electronic music producer.",
  "the basement jaxx": "A British electronic music duo.",
  "the underworld": "A British electronic music group.",
  "the orbital": "A British electronic music group.",
  "the kraftwerk": "A German electronic music band, pioneers of electronic music.",
  "kraftwerk": "A German electronic band formed in 1969.",
  "tangerine dream": "A German electronic music group.",
  "jean‑michel jarre": "A French electronic musician.",
  "vangelis": "A Greek electronic musician, known for the 'Chariots of Fire' theme.",
  "wim mertens": "A Belgian composer, known for minimal music.",
  "philip glass": "An American composer, known for minimal music.",
  "steve reich": "An American composer, known for minimalist music.",
  "terry riley": "An American composer, known for minimalist music.",
  "la monte young": "An American composer, known for minimalist and drone music.",
  "john cage": "An American composer, known for experimental music.",
  "morton feldman": "An American composer, known for his unique style.",
  "pierre boulez": "A French composer and conductor.",
  "karlheinz stockhausen": "A German composer, known for electronic music.",
  "györgy ligeti": "A Hungarian‑Austrian composer, known for his use of micropolyphony.",
  "franco donatoni": "An Italian composer.",
  "luciano berio": "An Italian composer.",
  "carlo boccadoro": "An Italian composer.",
  "enzo rossi": "An Italian composer.",
  "luigi nono": "An Italian composer.",
  "ilhan mimaroğlu": "A Turkish composer, known for electronic music.",
  "giorgio gori": "An Italian composer.",
  "federico sardella": "An Italian composer.",

  // ─── SPORTS & ATHLETES ──────────────────────────────────────────────
  "football": "Also known as soccer, the world's most popular sport, played with 11 players on each side.",
  "basketball": "A sport played with 5 players on each side, aiming to score by shooting a ball through a hoop.",
  "tennis": "A sport played with a racquet and ball, either singles or doubles.",
  "cricket": "A bat‑and‑ball game played with 11 players on each side, popular in the Commonwealth.",
  "rugby": "A contact sport with 15 players on each side, similar to American football.",
  "american football": "A sport played with 11 players on each side, involving throwing and carrying a ball.",
  "golf": "A sport where players hit a ball into a series of holes with as few strokes as possible.",
  "boxing": "A combat sport where two opponents fight with fists, wearing gloves.",
  "mixed martial arts": "A full‑contact combat sport allowing both striking and grappling.",
  "ufc": "Ultimate Fighting Championship, the largest MMA promotion.",
  "swimming": "A sport involving moving through water, with various strokes.",
  "athletics": "A sport involving running, jumping, throwing, and walking.",
  "skiing": "A sport involving gliding over snow on skis.",
  "snowboarding": "A sport where participants descend a snow‑covered slope on a board.",
  "ice hockey": "A sport played on ice with sticks and a puck, popular in Canada.",
  "field hockey": "A sport played on grass or turf with sticks and a ball.",
  "baseball": "A bat‑and‑ball game played between two teams of nine players.",
  "softball": "A variant of baseball with a larger ball and underhand pitching.",
  "lacrosse": "A contact sport played with a stick and ball, popular in North America.",
  "water polo": "A sport played in water where players throw a ball into a goal.",
  "handball": "A sport where players throw a ball into a goal, played indoors.",
  "volleyball": "A sport where two teams hit a ball over a net.",
  "beach volleyball": "A variant of volleyball played on sand.",
  "badminton": "A sport where players hit a shuttlecock over a net.",
  "table tennis": "A sport where players hit a small ball over a net on a table.",
  "squash": "A racquet sport played on an enclosed court.",
  "racquetball": "A racquet sport played on a four‑wall court.",
  "cycling": "A sport involving riding bicycles, including road racing and track cycling.",
  "triathlon": "A sport combining swimming, cycling, and running.",
  "marathon": "A long‑distance running race of 42.195 kilometres.",
  "sprinting": "Short‑distance running races, typically 100m, 200m, and 400m.",
  "long jump": "A track and field event where athletes jump as far as possible from a runway.",
  "high jump": "A track and field event where athletes jump over a bar.",
  "pole vault": "A track and field event where athletes use a pole to clear a bar.",
  "shot put": "A track and field event where athletes throw a heavy ball.",
  "discus": "A track and field event where athletes throw a discus.",
  "javelin": "A track and field event where athletes throw a javelin.",
  "hammer throw": "A track and field event where athletes throw a hammer.",
  "decathlon": "A combined event with ten track and field disciplines.",
  "heptathlon": "A combined event with seven track and field disciplines.",
  "gymnastics": "A sport involving acrobatic movements, performed on various apparatus.",
  "trampoline": "A sport where athletes perform acrobatics on a trampoline.",
  "diving": "A sport where athletes jump into water from a platform or springboard.",
  "synchronised swimming": "A sport where athletes perform choreographed moves in water.",
  "surfing": "A sport where participants ride waves on a surfboard.",
  "skateboarding": "A sport where athletes perform tricks on a skateboard.",
  "rock climbing": "A sport where athletes ascend rock faces, either indoors or outdoors.",
  "mountaineering": "The sport of climbing mountains.",
  "hiking": "Walking in natural environments, often on trails.",
  "fishing": "A sport involving catching fish, often for leisure.",
  "hunting": "The practice of pursuing wild animals for food or sport.",
  "archery": "A sport where athletes shoot arrows at a target.",
  "shooting": "A sport where athletes fire firearms at targets.",
  "fencing": "A combat sport with swords (foil, épée, sabre).",
  "judo": "A martial art and combat sport involving throws and grappling.",
  "karate": "A martial art focusing on striking, kicking, and blocking.",
  "taekwondo": "A Korean martial art with a focus on kicks.",
  "muay thai": "A Thai martial art and combat sport, also known as 'the art of eight limbs'.",
  "kickboxing": "A combat sport combining boxing and martial arts kicks.",
  "wrestling": "A combat sport involving grappling and submissions.",
  "sumo": "A Japanese wrestling sport where athletes try to push each other out of a ring.",
  "bjj": "Brazilian Jiu‑Jitsu, a grappling martial art.",
  "capoeira": "A Brazilian martial art combining dance and acrobatics.",
  "kendo": "A Japanese martial art using bamboo swords.",
  "aikido": "A Japanese martial art focusing on using the opponent's energy.",
  "kenpo": "A martial art originating in Hawaii.",
  "ninjutsu": "A Japanese martial art associated with the ninja.",
  "pencak silat": "A Southeast Asian martial art.",
  "krav maga": "An Israeli martial art used in self‑defense.",
  "systema": "A Russian martial art.",
  "sambo": "A Russian martial art and combat sport.",
  "shootfighting": "A combat sport combining wrestling and striking.",
  "pankration": "An ancient Greek martial art.",
  "nunchaku": "A weapon used in martial arts, also a practice.",
  "bo staff": "A long wooden staff used in martial arts.",
  "kali": "A Filipino martial art.",
  "escrima": "A Filipino martial art involving stick fighting.",
  "arnis": "The national martial art of the Philippines.",
  "silat": "A Southeast Asian martial art.",
  "bando": "A Burmese martial art.",
  "thai boxing": "Another name for Muay Thai.",
  "cung le": "A Vietnamese‑American martial artist.",
  "bruce lee": "A martial artist, actor, and founder of Jeet Kune Do.",
  "jackie chan": "A Hong Kong actor and martial artist.",
  "jet li": "A Chinese actor and martial artist.",
  "donnie yen": "A Hong Kong actor and martial artist.",
  "tony jaa": "A Thai actor and martial artist.",
  "scott adkins": "An English actor and martial artist.",
  "michael jai white": "An American actor and martial artist.",
  "wesley snipes": "An American actor and martial artist.",
  "steven seagal": "An American actor and martial artist.",
  "jean‑claude van damme": "A Belgian actor and martial artist.",
  "chuck norris": "An American actor and martial artist.",
  "sylvester stallone": "An American actor, known for Rocky and Rambo.",
  "arnold schwarzenegger": "An Austrian‑American actor and bodybuilder.",
  "dwayne johnson": "An American actor and former professional wrestler.",
  "john cena": "An American actor and professional wrestler.",
  "the rock": "Dwayne Johnson's wrestling alias.",
  "hulk hogan": "An American professional wrestler.",
  "stone cold steve austin": "An American professional wrestler.",
  "undertaker": "An American professional wrestler.",
  "triple h": "An American professional wrestler.",
  "shawn michaels": "An American professional wrestler.",
  "brett hart": "A Canadian professional wrestler.",
  "mick foley": "An American professional wrestler.",
  "kurt angle": "An American professional wrestler.",
  "randy orton": "An American professional wrestler.",
  "batista": "An American professional wrestler.",
  "edge": "A Canadian professional wrestler.",
  "daniel bryan": "An American professional wrestler.",
  "cm punk": "An American professional wrestler.",
  "aj styles": "An American professional wrestler.",
  "kenny omega": "A Canadian professional wrestler.",
  "okada": "A Japanese professional wrestler.",
  "tanahashi": "A Japanese professional wrestler.",
  "nakamura": "A Japanese professional wrestler.",
  "hiroshi tanahashi": "A Japanese professional wrestler.",
  "kota ibushi": "A Japanese professional wrestler.",
  "will ospreay": "A British professional wrestler.",
  "ric flair": "An American professional wrestler.",
  "roddy piper": "A Canadian professional wrestler.",
  "rowdy roddy piper": "A Canadian professional wrestler.",
  "andy murray": "A British tennis player.",
  "novak djokovic": "A Serbian tennis player, one of the greatest of all time.",
  "roger federer": "A Swiss tennis player, known for his elegance.",
  "rafael nadal": "A Spanish tennis player, known for his dominance on clay.",
  "serena williams": "An American tennis player, one of the greatest female players.",
  "venus williams": "An American tennis player, sister of Serena.",
  "maria sharapova": "A Russian tennis player.",
  "simona halep": "A Romanian tennis player.",
  "garbiñe muguruza": "A Spanish tennis player.",
  "naomi osaka": "A Japanese tennis player.",
  "coco gauff": "An American tennis player.",
  "emma raducanu": "A British tennis player.",
  "leila fernandez": "A Canadian tennis player.",
  "bianca andreescu": "A Canadian tennis player.",
  "ash barty": "An Australian tennis player.",
  "petra kvitová": "A Czech tennis player.",
  "karolína plíšková": "A Czech tennis player.",
  "angelique kerber": "A German tennis player.",
  "victoria azarenka": "A Belarusian tennis player.",
  "sloane stephens": "An American tennis player.",
  "madison keys": "An American tennis player.",
  "danielle collins": "An American tennis player.",
  "garbine muguruza": "A Spanish tennis player.",
  "jelena ostapenko": "A Latvian tennis player.",
  "elena rybakina": "A Kazakhstani tennis player.",
  "aryna sabalenka": "A Belarusian tennis player.",
  "iga swiatek": "A Polish tennis player.",
  "rafael nadal": "Spanish tennis player.",
  "novak djokovic": "Serbian tennis player.",
  "roger federer": "Swiss tennis player.",
  "andy murray": "British tennis player.",
  "dominik thiem": "Austrian tennis player.",
  "juan martin del potro": "Argentine tennis player.",
  "stan wawrinka": "Swiss tennis player.",
  "marin cilic": "Croatian tennis player.",
  "daniil medvedev": "Russian tennis player.",
  "alexander zverev": "German tennis player.",
  "stefanos tsitsipas": "Greek tennis player.",
  "matteo berrettini": "Italian tennis player.",
  "hubi hurkacz": "Polish tennis player.",
  "cameron norrie": "British tennis player.",
  "félix auger‑aliassime": "Canadian tennis player.",
  "denis shapovalov": "Canadian tennis player.",
  "jannik sinner": "Italian tennis player.",
  "carlos alcaraz": "Spanish tennis player.",
  "holger rune": "Danish tennis player.",
  "lorenzo musetti": "Italian tennis player.",
  "sebastian korda": "American tennis player.",
  "taylor fritz": "American tennis player.",
  "frances tiafoe": "American tennis player.",
  "tommy paul": "American tennis player.",
  "bublik": "Kazakhstani tennis player.",
  "kwon soon‑woo": "South Korean tennis player.",
  "yoshihito nishioka": "Japanese tennis player.",
  "kei nishikori": "Japanese tennis player.",
  "yevgeny kafelnikov": "Russian tennis player, former world No. 1.",
  "marat safin": "Russian tennis player, former world No. 1.",
  "gustavo kuerten": "Brazilian tennis player.",
  "jim courier": "American tennis player.",
  "michael chang": "American tennis player.",
  "jimmy connors": "American tennis player.",
  "john mcenroe": "American tennis player.",
  "björn borg": "Swedish tennis player.",
  "rod laver": "Australian tennis player.",
  "ken rosewall": "Australian tennis player.",
  "roy emerson": "Australian tennis player.",
  "neale fraser": "Australian tennis player.",
  "lew hoad": "Australian tennis player.",
  "john newcombe": "Australian tennis player.",
  "tony roche": "Australian tennis player.",
  "pat cash": "Australian tennis player.",
  "mark edmondson": "Australian tennis player.",
  "pat rafter": "Australian tennis player.",
  "leyton hewitt": "Australian tennis player.",
  "bernard tomic": "Australian tennis player.",
  "thanasi kokkinakis": "Australian tennis player.",
  "alex de minaur": "Australian tennis player.",
  "nick kyrgios": "Australian tennis player.",
  "matthew ebden": "Australian tennis player.",
  "john millman": "Australian tennis player.",
  "jordan thompson": "Australian tennis player.",
  "alexei popyrin": "Australian tennis player.",
  "james duckworth": "Australian tennis player.",
  "max purcell": "Australian tennis player.",
  "luke saville": "Australian tennis player.",
  "tomic": "Australian tennis player.",

  // ─── INVENTIONS & DISCOVERIES ──────────────────────────────────────
  "wheel": "Invented around 3500 BCE in Mesopotamia, revolutionised transport and machinery.",
  "printing press": "Invented by Johannes Gutenberg around 1440, enabling mass production of books.",
  "compass": "Invented in ancient China, used for navigation.",
  "gunpowder": "Discovered in China around the 9th century, used in fireworks and weaponry.",
  "paper": "Invented in China around 105 CE, spread to the Arab world and Europe.",
  "steam engine": "Developed in the 18th century, powered the Industrial Revolution.",
  "light bulb": "Perfected by Thomas Edison in 1879, though earlier designs existed.",
  "telephone": "Patented by Alexander Graham Bell in 1876.",
  "radio": "Developed by Guglielmo Marconi in the 1890s, enabling wireless communication.",
  "television": "Invented by John Logie Baird in the 1920s, later improved by others.",
  "computer": "Early mechanical computers like the Babbage Analytical Engine, modern ones developed in the 1940s.",
  "internet": "Evolved from ARPANET in the 1960s, became public in the 1990s.",
  "world wide web": "Invented by Tim Berners‑Lee in 1989.",
  "smartphone": "Early models in the 1990s, but the iPhone (2007) popularised the modern form.",
  "automobile": "Developed in the late 19th century, with Karl Benz's Motorwagen in 1885.",
  "airplane": "The Wright brothers flew the first powered aircraft in 1903.",
  "rocket": "Early rockets in China, modern rocketry developed by Robert Goddard and others.",
  "nuclear fission": "Discovered in 1938, led to nuclear power and weapons.",
  "penicillin": "Discovered by Alexander Fleming in 1928, revolutionised medicine.",
  "vaccine": "Developed by Edward Jenner for smallpox in 1796.",
  "dna structure": "Discovered by James Watson and Francis Crick in 1953, with contributions from Rosalind Franklin.",
  "theory of relativity": "Proposed by Albert Einstein in 1905 and 1915.",
  "quantum mechanics": "Developed in the early 20th century by Planck, Bohr, Heisenberg, Schrödinger, etc.",
  "evolution by natural selection": "Proposed by Charles Darwin in 1859.",
  "germ theory": "Established by Louis Pasteur and Robert Koch in the 19th century.",
  "periodic table": "Developed by Dmitri Mendeleev in 1869.",
  "radioactivity": "Discovered by Henri Becquerel in 1896, further studied by Marie and Pierre Curie.",
  "x‑rays": "Discovered by Wilhelm Röntgen in 1895.",
  "electromagnetic induction": "Discovered by Michael Faraday in 1831.",
  "electric motor": "Developed by Faraday and others.",
  "dynamo": "A device that converts mechanical energy to electrical energy, developed by Faraday.",
  "generator": "A device that converts mechanical energy to electrical energy.",
  "transformer": "Developed by Nikola Tesla and others.",
  "alternating current": "Developed by Nikola Tesla.",
  "radio": "Developed by Marconi.",
  "radar": "Developed in the 1930s, used in WWII.",
  "sonar": "Developed in the early 20th century.",
  "laser": "Invented by Theodore Maiman in 1960, though earlier concepts existed.",
  "fibre optics": "Developed in the 1960s, enabling high‑speed communication.",
  "microscope": "Early versions in the 16th century, improved by Leeuwenhoek.",
  "telescope": "Invented by Hans Lippershey in 1608, improved by Galileo.",
  "thermometer": "Developed by Galileo, Santorio, and others in the 16‑17th centuries.",
  "barometer": "Invented by Evangelista Torricelli in 1643.",
  "steam turbine": "Developed by Charles Parsons in 1884.",
  "internal combustion engine": "Developed by Nikolaus Otto in 1876.",
  "diesel engine": "Invented by Rudolf Diesel in 1892.",
  "jet engine": "Developed by Frank Whittle and Hans von Ohain in the 1930s.",
  "helicopter": "Early designs by Leonardo da Vinci, modern helicopters developed in the 20th century.",
  "submarine": "Early submarines in the 17th century, modern ones in the 19th century.",
  "diving suit": "Developed in the 19th century.",
  "scuba gear": "Developed by Jacques‑Yves Cousteau in the 1940s.",
  "safety match": "Invented by John Walker in 1826.",
  "zipper": "Patented by Gideon Sundback in 1913.",
  "velcro": "Invented by George de Mestral in 1941.",
  "ballpoint pen": "Patented by László Bíró in 1938.",
  "fountain pen": "Invented by Petrache Poenaru in 1827.",
  "pencil": "Evolved from early writing tools, modern version in the 16th century.",
  "typewriter": "Developed in the 19th century.",
  "calculator": "Early mechanical calculators, electronic ones in the 1960s.",
  "abacus": "An ancient calculating tool.",
  "clock": "Ancient timekeeping, mechanical clocks in the 14th century.",
  "watch": "Portable clocks developed in the 16th century.",
  "pendulum clock": "Invented by Christiaan Huygens in 1656.",
  "quartz clock": "Developed in the 1920s.",
  "atomic clock": "Developed in the 1950s, highly accurate.",
  "battery": "Invented by Alessandro Volta in 1800.",
  "electric car": "Early electric vehicles in the 19th century, modern resurgence.",
  "petrol engine": "Developed in the late 19th century.",
  "diesel engine": "Invented by Rudolf Diesel.",
  "steam locomotive": "Developed by George Stephenson in the early 19th century.",
  "bicycle": "Developed in the 19th century.",
  "motorcycle": "Developed in the late 19th century.",
  "elevator": "Safety elevator invented by Elisha Otis in 1852.",
  "escalator": "Patented by Charles Seeberger in 1900.",
  "moving walkway": "Developed in the late 19th century.",
  "skyscraper": "Early tall buildings in the late 19th century.",
  "suspension bridge": "Modern suspension bridges developed in the 19th century.",
  "concrete": "Used by Romans, modern cement patented in 1824.",
  "steel": "Modern steel production developed in the 19th century.",
  "aluminium": "Isolated in the 19th century, production became cheap later.",
  "plastic": "Early plastics like Bakelite in the early 20th century.",
  "nylon": "Developed by DuPont in 1935.",
  "polyethylene": "Developed in the 1930s.",
  "teflon": "Discovered by Roy Plunkett in 1938.",
  "velcro": "Invented by de Mestral.",
  "frisbee": "Invented by Walter Frederick Morrison in 1948.",
  "yo‑yo": "Ancient toy, popularised in the 20th century.",
  "hula hoop": "Popularised in the 1950s.",
  "slinky": "Invented by Richard James in 1943.",
  "magnatiles": "A construction toy.",
  "lego": "Developed in 1932 by Ole Kirk Christiansen.",
  "rubik's cube": "Invented by Ernő Rubik in 1974.",
  "fidget spinner": "Popularised in 2017, but similar toys existed earlier.",
  "computer mouse": "Invented by Douglas Engelbart in 1964.",
  "graphical user interface": "Developed at Xerox PARC in the 1970s, popularised by Apple.",
  "touchscreen": "Developed in the 1960s, modern capacitive screens in the 2000s.",
  "voice assistant": "Siri (2011), Alexa (2014), Google Assistant (2016).",
  "digital camera": "Developed in the 1970s, consumer models in the 1990s.",
  "photography": "First permanent photograph in 1826 by Nicéphore Niépce.",
  "film": "Developed in the late 19th century.",
  "sound recording": "First audio recording in 1860, phonograph in 1877.",
  "motion picture": "First films in the 1890s.",
  "colour film": "Developed in the early 20th century.",
  "television broadcast": "First public broadcasts in the 1920s.",
  "satellite": "Sputnik 1 in 1957.",
  "space travel": "Yuri Gagarin orbited Earth in 1961.",
  "moon landing": "Apollo 11 in 1969.",
  "space station": "Skylab (1973), Mir (1986), ISS (1998).",
  "reusable rocket": "Developed by SpaceX in the 2010s.",
  "drones": "UAVs developed in the 20th century, popular in the 2000s.",
  "robotics": "Developed in the 20th century, industrial robots in the 1960s.",
  "artificial intelligence": "Term coined in 1956, modern advancements in the 2010s.",
  "machine learning": "Subfield of AI, with neural networks developed in the 1980s.",
  "deep learning": "Popularised in the 2010s with advances in image recognition.",
  "natural language processing": "Used in chatbots and translation.",
  "computer vision": "Used in image and video analysis.",
  "virtual reality": "Early headsets in the 1990s, modern ones in the 2010s.",
  "augmented reality": "Pokémon Go (2016) popularised it.",
  "blockchain": "Developed for Bitcoin in 2008.",
  "cryptocurrency": "Bitcoin launched in 2009.",
  "etherum": "A blockchain platform launched in 2015.",
  "smart contracts": "Developed on Ethereum.",
  "3d printing": "Developed in the 1980s, consumer models in the 2000s.",
  "biodegradable plastic": "Developed in the late 20th century.",
  "renewable energy": "Solar, wind, hydro power developed throughout the 20th century.",
  "solar cell": "First practical solar cell in 1954.",
  "wind turbine": "Modern designs in the 1970s.",
  "hydroelectric power": "Developed in the 19th century.",
  "geothermal energy": "Used in the 20th century.",
  "fusion energy": "Ongoing research, not yet practical.",
  "nuclear reactor": "First operational in 1942, used for power from 1954.",
  "nuclear bomb": "Developed in 1945.",
  "hydrogen bomb": "Developed in 1952.",
  "gene editing": "CRISPR‑Cas9 developed in 2012.",
  "cloning": "Dolly the sheep cloned in 1996.",
  "stem cell research": "Developed in the late 20th century.",
  "pacemaker": "Invented in 1950.",
  "mri": "Developed in the 1970s.",
  "ct scan": "Developed in the 1970s.",
  "x‑ray machine": "Developed shortly after X‑rays were discovered.",
  "defibrillator": "Developed in the 1930s.",
  "insulin": "Discovered in 1921, used to treat diabetes.",
  "antibiotics": "Penicillin discovered in 1928, mass‑produced in the 1940s.",
  "antiviral drugs": "Developed in the 1960s.",
  "vaccines": "Developed for many diseases throughout the 20th century.",
  "oral contraceptive pill": "Approved in 1960.",
  "ivf": "First successful in 1978.",
  "organ transplant": "First successful kidney transplant in 1954.",
  "heart transplant": "First successful in 1967.",
  "artificial heart": "First implanted in 1982.",
  "bionic eye": "Research in the 2000s.",
  "bionic ear": "Cochlear implants in the 1970s.",
  "prosthetics": "Modern prosthetics with microprocessors in the 2000s.",
  "exoskeleton": "Developed for rehabilitation.",
  "genetic testing": "Available since the 1990s.",
  "personalised medicine": "Based on genetic profiling.",
  "nanotechnology": "Developed in the 1980s.",
  "biotechnology": "Developed in the 1970s.",
  "agriculture": "Farming revolutionised by machinery and fertilisers in the 19‑20th centuries.",
  "green revolution": "In the 1960s, increased crop yields.",
  "vertical farming": "Modern concept.",
  "hydroponics": "Soil‑less farming developed in the 1930s.",
  "aquaponics": "Combines aquaculture and hydroponics.",

  // ─── GEOGRAPHY: RIVERS, MOUNTAINS, OCEANS, LANDMARKS ────────────────
  "amazon river": "The largest river by volume, flowing through South America, about 6,400 km long.",
  "nile river": "The longest river in the world, about 6,650 km, flowing through Africa.",
  "mississippi river": "A major river in North America, about 3,730 km.",
  "yangtze river": "The longest river in Asia, about 6,300 km, flowing through China.",
  "yellow river": "A major river in China, about 5,464 km, known as the cradle of Chinese civilisation.",
  "danube river": "A river in Europe, flowing through 10 countries, about 2,850 km.",
  "rhine river": "A major European river, about 1,230 km, flowing through Germany and the Netherlands.",
  "seine river": "A river in France, flowing through Paris.",
  "thames river": "A river in England, flowing through London.",
  "ganges river": "A sacred river in India, about 2,525 km.",
  "brahmaputra river": "A river in Asia, flowing through Tibet, India, and Bangladesh.",
  "indus river": "A river in South Asia, about 3,180 km.",
  "tigris river": "A river in the Middle East, part of the ancient Mesopotamian region.",
  "euphrates river": "A river in the Middle East, paired with the Tigris.",
  "niger river": "A major river in West Africa, about 4,180 km.",
  "congo river": "The second‑longest river in Africa, about 4,700 km, with the second‑largest volume.",
  "zambezi river": "A river in Africa, about 2,574 km, famous for Victoria Falls.",
  "volga river": "The longest river in Europe, about 3,530 km, flowing through Russia.",
  "mekong river": "A river in Southeast Asia, about 4,350 km.",
  "murray river": "The longest river in Australia, about 2,508 km.",
  "danube river": "Flows through central and eastern Europe.",
  "rhine river": "Flows through western Europe.",
  "elbe river": "Flows through Germany and the Czech Republic.",
  "oder river": "Flows through Poland and Germany.",
  "vistula river": "The longest river in Poland.",
  "po river": "The longest river in Italy.",
  "tiber river": "A river in Italy, flowing through Rome.",
  "loire river": "The longest river in France.",
  "garonne river": "A river in southwestern France.",
  "douro river": "A river in Spain and Portugal.",
  "tagus river": "The longest river in the Iberian Peninsula.",
  "guadalquivir river": "A river in Spain.",
  "ebro river": "A river in Spain.",
  "rhone river": "A river in France and Switzerland.",
  "socoa river": "A river in France.",
  "siene river": "A river in France.",
  "marne river": "A river in France.",
  "aare river": "A river in Switzerland.",
  "reuss river": "A river in Switzerland.",
  "limmat river": "A river in Switzerland.",
  "töss river": "A river in Switzerland.",
  "glatt river": "A river in Switzerland.",
  "sihl river": "A river in Switzerland.",
  "rhine river": "One of Europe's most important waterways.",
  "danube river": "Flows through central and eastern Europe.",
  "elbe river": "Flows through Germany.",
  "oder river": "Flows through Poland and Germany.",
  "vistula river": "Flows through Poland.",
  "po river": "Flows through Italy.",
  "tiber river": "Flows through Rome.",
  "thames river": "Flows through London.",
  "seine river": "Flows through Paris.",
  "loire river": "Flows through France.",
  "gironde": "An estuary in France.",
  "saint lawrence river": "A major river in Canada, flowing into the Atlantic.",
  "mackenzie river": "The longest river in Canada.",
  "yukon river": "A river in Canada and the US.",
  "columbia river": "A river in North America.",
  "colorado river": "A river in the US and Mexico, known for the Grand Canyon.",
  "rio grande": "A river in the US and Mexico, forming part of the border.",
  "amazon river": "The largest river by volume.",
  "orinoco river": "A river in South America.",
  "paraná river": "A river in South America.",
  "uruguay river": "A river in South America.",
  "rio de la plata": "An estuary in South America.",
  "magdalena river": "A river in Colombia.",
  "cauca river": "A river in Colombia.",
  "darien river": "A river in Panama.",
  "são francisco river": "A river in Brazil.",
  "tocantins river": "A river in Brazil.",
  "araguaia river": "A river in Brazil.",
  "madeira river": "A river in Brazil and Bolivia.",
  "purus river": "A river in Brazil and Peru.",
  "juruá river": "A river in Peru and Brazil.",
  "negro river": "A river in the Amazon basin.",
  "xingu river": "A river in Brazil.",
  "tapajós river": "A river in Brazil.",
  "congo river": "The second‑largest river in Africa.",
  "niger river": "A major West African river.",
  "zambezi river": "Famous for Victoria Falls.",
  "okavango river": "A river in Africa that ends in a delta.",
  "orange river": "A river in South Africa.",
  "limpopo river": "A river in South Africa.",
  "zambezi river": "Flows through Zimbabwe and Mozambique.",
  "rufiji river": "A river in Tanzania.",
  "tana river": "A river in Kenya.",
  "juba river": "A river in Somalia.",
  "shabelle river": "A river in Ethiopia and Somalia.",
  "ganges river": "Sacred in Hinduism.",
  "brahmaputra river": "Flows through India and Bangladesh.",
  "indus river": "Flows through Pakistan.",
  "tigris river": "Part of Mesopotamia.",
  "euphrates river": "Part of Mesopotamia.",
  "mekong river": "Flows through Southeast Asia.",
  "yangtze river": "Longest in Asia.",
  "yellow river": "Cradle of Chinese civilization.",
  "amur river": "Flows through Russia and China.",
  "lena river": "A river in Siberia.",
  "ob river": "A river in Siberia.",
  "yenisei river": "A river in Siberia.",
  "kolyma river": "A river in Siberia.",
  "indigirka river": "A river in Siberia.",
  "alazeya river": "A river in Siberia.",
  "kuray river": "A river in Turkey.",
  "kızılırmak river": "A river in Turkey.",
  "sakarya river": "A river in Turkey.",
  "çoruh river": "A river in Turkey.",
  "yeşilırmak river": "A river in Turkey.",
  "himalayas": "The highest mountain range in the world, including Mount Everest (8,848 m).",
  "mount everest": "The highest mountain on Earth, at 8,848 metres, in the Himalayas.",
  "k2": "The second‑highest mountain, at 8,611 metres, in the Karakoram range.",
  "kangchenjunga": "The third‑highest mountain, at 8,586 metres.",
  "lhotse": "The fourth‑highest mountain, at 8,516 metres.",
  "makalu": "The fifth‑highest mountain, at 8,485 metres.",
  "cho oyu": "The sixth‑highest mountain, at 8,188 metres.",
  "dhaulagiri": "The seventh‑highest mountain, at 8,167 metres.",
  "manaslu": "The eighth‑highest mountain, at 8,163 metres.",
  "nanga parbat": "The ninth‑highest mountain, at 8,126 metres.",
  "annapurna": "A mountain in the Himalayas, at 8,091 metres.",
  "broad peak": "A mountain in the Karakoram, at 8,051 metres.",
  "gasherbrum i": "A mountain in the Karakoram, at 8,068 metres.",
  "gasherbrum ii": "A mountain in the Karakoram, at 8,034 metres.",
  "shishapangma": "A mountain in the Himalayas, at 8,027 metres.",
  "rocky mountains": "A major mountain range in North America, stretching from Canada to the US.",
  "andes": "The longest continental mountain range, along the western edge of South America.",
  "alps": "A mountain range in Europe, stretching across several countries.",
  "pyrenees": "A mountain range between France and Spain.",
  "urals": "A mountain range in Russia, separating Europe and Asia.",
  "caucasus": "A mountain range between Europe and Asia, home to Mount Elbrus.",
  "mount elbrus": "The highest mountain in Europe, at 5,642 metres, in the Caucasus.",
  "mount fuji": "The highest mountain in Japan, at 3,776 metres, a stratovolcano.",
  "mount kilimanjaro": "The highest mountain in Africa, at 5,895 metres.",
  "mount aconcagua": "The highest mountain in South America, at 6,960 metres.",
  "mount denali": "The highest mountain in North America, at 6,190 metres.",
  "mount vinson": "The highest mountain in Antarctica, at 4,892 metres.",
  "mount kosciuszko": "The highest mountain in Australia, at 2,228 metres.",
  "mount everest": "The highest mountain in the world.",
  "k2": "The second‑highest mountain.",
  "kangchenjunga": "The third‑highest mountain.",
  "lhotse": "The fourth‑highest mountain.",
  "makalu": "The fifth‑highest mountain.",
  "cho oyu": "The sixth‑highest mountain.",
  "dhaulagiri": "The seventh‑highest mountain.",
  "manaslu": "The eighth‑highest mountain.",
  "nanga parbat": "The ninth‑highest mountain.",
  "annapurna": "The tenth‑highest mountain.",
  "pacific ocean": "The largest ocean, covering about one‑third of Earth's surface.",
  "atlantic ocean": "The second‑largest ocean, separating the Americas from Europe and Africa.",
  "indian ocean": "The third‑largest ocean, bordered by Asia, Africa, and Australia.",
  "southern ocean": "The ocean surrounding Antarctica.",
  "arctic ocean": "The smallest and shallowest ocean, around the North Pole.",
  "mediterranean sea": "A sea connected to the Atlantic, surrounded by Europe, Asia, and Africa.",
  "caribbean sea": "A tropical sea in the Americas, bordered by the Caribbean islands.",
  "south china sea": "A sea in Southeast Asia, bordered by China, Vietnam, and the Philippines.",
  "dead sea": "A salt lake bordered by Jordan and Israel, the lowest point on land.",
  "caspian sea": "The world's largest inland body of water, a lake, between Europe and Asia.",
  "lake baikal": "The deepest lake in the world, in Siberia.",
  "great lakes": "A group of five freshwater lakes in North America (Superior, Michigan, Huron, Erie, Ontario).",
  "lake superior": "The largest of the Great Lakes.",
  "lake michigan": "The third‑largest of the Great Lakes, entirely within the US.",
  "lake huron": "The second‑largest of the Great Lakes.",
  "lake erie": "The fourth‑largest of the Great Lakes.",
  "lake ontario": "The smallest of the Great Lakes.",
  "lake victoria": "The largest lake in Africa, bordering Uganda, Kenya, and Tanzania.",
  "lake tanganyika": "A large lake in Africa, the second‑deepest.",
  "lake malawi": "A lake in Africa, known for its biodiversity.",
  "great salt lake": "A saltwater lake in Utah, US.",
  "salton sea": "A saltwater lake in California.",
  "lake titicaca": "The highest navigable lake in the world, in the Andes.",
  "lake nicaragua": "The largest lake in Central America.",
  "lake maracaibo": "A lake in Venezuela.",
  "lake chad": "A lake in Africa, shrinking over time.",
  "lake aral": "A lake in Central Asia, formerly one of the largest, now largely dried up.",
  "lake baikal": "The deepest lake.",
  "caspian sea": "The largest lake.",
  "dead sea": "The lowest point on land.",
  "victoria falls": "A waterfall on the Zambezi River, one of the largest in the world.",
  "niagara falls": "A group of three waterfalls on the border of the US and Canada.",
  "iguazu falls": "A waterfall on the border of Argentina and Brazil.",
  "angel falls": "The highest waterfall in the world, at 979 metres, in Venezuela.",
  "yosemite falls": "A famous waterfall in Yosemite National Park, US.",
  "yellowstone national park": "The first national park in the world, in the US, known for geysers.",
  "grand canyon": "A massive canyon in the US, carved by the Colorado River.",
  "grand canyon national park": "A national park in the US.",
  "sahara desert": "The largest hot desert in the world, in Africa.",
  "gobi desert": "A large desert in Asia, spanning China and Mongolia.",
  "arabian desert": "A desert in the Middle East.",
  "kalahari desert": "A desert in Southern Africa.",
  "mojave desert": "A desert in the southwestern US.",
  "atacama desert": "The driest non‑polar desert, in Chile.",
  "antarctic desert": "The largest desert on Earth, a cold desert.",
  "great barrier reef": "The largest coral reef system, off the coast of Australia.",
  "mariana trench": "The deepest oceanic trench, in the Pacific Ocean.",
  "challenger deep": "The deepest point in the ocean, at about 10,994 metres, in the Mariana Trench.",
  "eiffel tower": "A landmark in Paris, France, built in 1889.",
  "taj mahal": "A mausoleum in Agra, India, built in the 17th century.",
  "great wall of china": "A series of fortifications in China, over 13,000 miles long.",
  "christ the redeemer": "A statue of Jesus in Rio de Janeiro, Brazil.",
  "machu picchu": "An ancient Inca city in Peru, built in the 15th century.",
  "colosseum": "An ancient Roman amphitheatre in Rome, Italy.",
  "chichen itza": "A Mayan city in Mexico, with the famous pyramid.",
  "stonehenge": "A prehistoric monument in England, dating back to 3000 BCE.",
  "pyramids of giza": "Ancient Egyptian pyramids, including the Great Pyramid.",
  "sphinx": "A statue with a lion's body and a human head, in Giza, Egypt.",
  "acropolis": "An ancient citadel in Athens, Greece.",
  "parthenon": "A temple on the Acropolis, dedicated to Athena.",
  "angkor wat": "A temple complex in Cambodia, built in the 12th century.",
  "petra": "An ancient city in Jordan, carved into rock.",
  "statue of liberty": "A statue in New York Harbor, a symbol of freedom.",
  "empire state building": "A famous skyscraper in New York City.",
  "burj khalifa": "The tallest building in the world, in Dubai, at 828 metres.",
  "london eye": "A giant Ferris wheel in London, UK.",
  "big ben": "The nickname for the Great Clock of Westminster, in London.",
  "tower bridge": "A combined bascule and suspension bridge in London.",
  "notre dame": "A gothic cathedral in Paris, France.",
  "sagrada familia": "A large Roman Catholic church in Barcelona, Spain, by Gaudí.",
  "sydney opera house": "A performing arts centre in Sydney, Australia.",
  "golden gate bridge": "A suspension bridge in San Francisco, US.",
  "mount rushmore": "A sculpture with the faces of four US presidents.",
  "uluru": "A large sandstone rock formation in Australia, also known as Ayers Rock.",
  "stonehenge": "A prehistoric monument in the UK.",
  "easter island statues": "Moai statues on Easter Island.",
  "tower of pisa": "A leaning tower in Italy.",
  "leaning tower of pisa": "A freestanding bell tower in Pisa, Italy, known for its tilt.",
  "forbidden city": "A palace complex in Beijing, China.",
  "taj mahal": "A mausoleum in India.",
  "red square": "A city square in Moscow, Russia.",
  "kremlin": "A fortified complex in Moscow, the seat of the Russian government.",
  "winter palace": "A palace in St. Petersburg, Russia.",
  "hermitage museum": "One of the largest art museums in the world, in St. Petersburg.",
  "louvre": "The world's largest art museum, in Paris.",
  "british museum": "A museum in London, housing world history and culture.",
  "vatican museums": "Museums in Vatican City, home to the Sistine Chapel.",
  "sistine chapel": "A chapel in Vatican City, famous for Michelangelo's ceiling.",
  "the white house": "The official residence of the US president, in Washington, D.C.",
  "the pentagon": "The headquarters of the US Department of Defense.",
  "the capitol": "The seat of the US Congress.",
  "the louvre": "Art museum in Paris.",
  "the met": "The Metropolitan Museum of Art in New York.",
  "the rijk museum": "A national museum in Amsterdam.",
  "the prado": "A national museum in Madrid.",
  "the uffizi": "An art museum in Florence, Italy.",
  "the hermitage": "An art museum in St. Petersburg.",
  "the victoria and albert museum": "A museum of decorative arts in London.",
  "the tate modern": "A modern art museum in London.",
  "the pompidou centre": "A cultural centre in Paris.",
  "the guggenheim": "A museum of modern art in New York and elsewhere.",
};

// ─────────────────────────────────────────────────────────────────────────────
// LOOKUP FUNCTION
// ─────────────────────────────────────────────────────────────────────────────

function lookupMoreKnowledge(topic) {
  const key = topic.toLowerCase().trim();
  if (MORE_KNOWLEDGE[key]) return MORE_KNOWLEDGE[key];
  if (key.endsWith('s')) {
    const singular = key.slice(0, -1);
    if (MORE_KNOWLEDGE[singular]) return MORE_KNOWLEDGE[singular];
  }
  if (key.startsWith('the ')) {
    const withoutThe = key.slice(4);
    if (MORE_KNOWLEDGE[withoutThe]) return MORE_KNOWLEDGE[withoutThe];
  }
  return null;
}

// ─────────────────────────────────────────────────────────────────────────────
// HANDLER – same regex and structure as the base one
// ─────────────────────────────────────────────────────────────────────────────

const WHAT_IS_MORE_KNOWLEDGE_REGEX = /\bwhat is (a|an|the)?\s*([a-zA-Z][a-zA-Z0-9_ ]{2,40})\??$/i;

function whatIsMoreKnowledgeResponse(msg, p) {
  const match = msg.match(WHAT_IS_MORE_KNOWLEDGE_REGEX);
  if (!match) return null;
  const topic = match[2].trim();
  const entry = lookupMoreKnowledge(topic);
  if (!entry) return null;

  const R = [
    [`${topic}: ${entry}`, `That's ${topic}. ${entry}`, `${topic} – ${entry}`],
    [`${topic} – ${entry}`, `${topic} is ${entry}`, `Yes, ${topic}: ${entry}`],
    [`${topic} is ${entry} – but what does it matter?`, `${topic}: ${entry} – interesting, right?`, `${topic} is ${entry}. Not that it helps.`],
    [`${topic} – ${entry}. You should know that.`, `${topic} is ${entry}. It won't save you.`, `${topic}: ${entry}. That's the fact.`],
    [`${topic} is ${entry}. I'm glad you asked.`, `${topic} – I know about it. ${entry}`, `${topic}: ${entry}. That's the truth.`],
    [`${topic} – ${entry}. I've known that for ages.`, `${topic} is ${entry}. And that's all you need.`],
  ];
  return pick(ph(R, p));
}

// ─────────────────────────────────────────────────────────────────────────────
// EXPORT
// ─────────────────────────────────────────────────────────────────────────────

export {
  WHAT_IS_MORE_KNOWLEDGE_REGEX,
  whatIsMoreKnowledgeResponse,
  MORE_KNOWLEDGE, // optional, if you want to merge with the base
};